// Each city entry: { city, region, regionCode, macroRegion }
// region   = full name of the state/region (used for "Boston, Massachusetts")
// regionCode = short code used as a key for region-bucketed pools (high schools)
// macroRegion = broader bucket used for college lookup
export const CITIES = [
  // Northeast
  { city: "New York", region: "New York", regionCode: "NY", macroRegion: "northeast" },
  { city: "Brooklyn", region: "New York", regionCode: "NY", macroRegion: "northeast" },
  { city: "Queens", region: "New York", regionCode: "NY", macroRegion: "northeast" },
  { city: "Buffalo", region: "New York", regionCode: "NY", macroRegion: "northeast" },
  { city: "Philadelphia", region: "Pennsylvania", regionCode: "PA", macroRegion: "northeast" },
  { city: "Pittsburgh", region: "Pennsylvania", regionCode: "PA", macroRegion: "northeast" },
  { city: "Boston", region: "Massachusetts", regionCode: "MA", macroRegion: "northeast" },
  { city: "Cambridge", region: "Massachusetts", regionCode: "MA", macroRegion: "northeast" },
  { city: "Providence", region: "Rhode Island", regionCode: "RI", macroRegion: "northeast" },
  { city: "Hartford", region: "Connecticut", regionCode: "CT", macroRegion: "northeast" },
  { city: "Newark", region: "New Jersey", regionCode: "NJ", macroRegion: "northeast" },
  { city: "Jersey City", region: "New Jersey", regionCode: "NJ", macroRegion: "northeast" },
  { city: "Baltimore", region: "Maryland", regionCode: "MD", macroRegion: "northeast" },
  { city: "Washington", region: "District of Columbia", regionCode: "DC", macroRegion: "northeast" },
  // Southeast
  { city: "Charlotte", region: "North Carolina", regionCode: "NC", macroRegion: "southeast" },
  { city: "Raleigh", region: "North Carolina", regionCode: "NC", macroRegion: "southeast" },
  { city: "Atlanta", region: "Georgia", regionCode: "GA", macroRegion: "southeast" },
  { city: "Savannah", region: "Georgia", regionCode: "GA", macroRegion: "southeast" },
  { city: "Miami", region: "Florida", regionCode: "FL", macroRegion: "southeast" },
  { city: "Orlando", region: "Florida", regionCode: "FL", macroRegion: "southeast" },
  { city: "Tampa", region: "Florida", regionCode: "FL", macroRegion: "southeast" },
  { city: "Jacksonville", region: "Florida", regionCode: "FL", macroRegion: "southeast" },
  { city: "Nashville", region: "Tennessee", regionCode: "TN", macroRegion: "southeast" },
  { city: "Memphis", region: "Tennessee", regionCode: "TN", macroRegion: "southeast" },
  { city: "Louisville", region: "Kentucky", regionCode: "KY", macroRegion: "southeast" },
  { city: "Richmond", region: "Virginia", regionCode: "VA", macroRegion: "southeast" },
  { city: "Virginia Beach", region: "Virginia", regionCode: "VA", macroRegion: "southeast" },
  { city: "Columbia", region: "South Carolina", regionCode: "SC", macroRegion: "southeast" },
  { city: "New Orleans", region: "Louisiana", regionCode: "LA", macroRegion: "southeast" },
  { city: "Birmingham", region: "Alabama", regionCode: "AL", macroRegion: "southeast" },
  // Midwest
  { city: "Chicago", region: "Illinois", regionCode: "IL", macroRegion: "midwest" },
  { city: "Naperville", region: "Illinois", regionCode: "IL", macroRegion: "midwest" },
  { city: "Detroit", region: "Michigan", regionCode: "MI", macroRegion: "midwest" },
  { city: "Grand Rapids", region: "Michigan", regionCode: "MI", macroRegion: "midwest" },
  { city: "Columbus", region: "Ohio", regionCode: "OH", macroRegion: "midwest" },
  { city: "Cleveland", region: "Ohio", regionCode: "OH", macroRegion: "midwest" },
  { city: "Cincinnati", region: "Ohio", regionCode: "OH", macroRegion: "midwest" },
  { city: "Indianapolis", region: "Indiana", regionCode: "IN", macroRegion: "midwest" },
  { city: "Milwaukee", region: "Wisconsin", regionCode: "WI", macroRegion: "midwest" },
  { city: "Madison", region: "Wisconsin", regionCode: "WI", macroRegion: "midwest" },
  { city: "Minneapolis", region: "Minnesota", regionCode: "MN", macroRegion: "midwest" },
  { city: "St. Paul", region: "Minnesota", regionCode: "MN", macroRegion: "midwest" },
  { city: "Kansas City", region: "Missouri", regionCode: "MO", macroRegion: "midwest" },
  { city: "St. Louis", region: "Missouri", regionCode: "MO", macroRegion: "midwest" },
  { city: "Omaha", region: "Nebraska", regionCode: "NE", macroRegion: "midwest" },
  // Southwest
  { city: "Dallas", region: "Texas", regionCode: "TX", macroRegion: "southwest" },
  { city: "Houston", region: "Texas", regionCode: "TX", macroRegion: "southwest" },
  { city: "Austin", region: "Texas", regionCode: "TX", macroRegion: "southwest" },
  { city: "San Antonio", region: "Texas", regionCode: "TX", macroRegion: "southwest" },
  { city: "Fort Worth", region: "Texas", regionCode: "TX", macroRegion: "southwest" },
  { city: "El Paso", region: "Texas", regionCode: "TX", macroRegion: "southwest" },
  { city: "Phoenix", region: "Arizona", regionCode: "AZ", macroRegion: "southwest" },
  { city: "Tucson", region: "Arizona", regionCode: "AZ", macroRegion: "southwest" },
  { city: "Las Vegas", region: "Nevada", regionCode: "NV", macroRegion: "southwest" },
  { city: "Henderson", region: "Nevada", regionCode: "NV", macroRegion: "southwest" },
  { city: "Albuquerque", region: "New Mexico", regionCode: "NM", macroRegion: "southwest" },
  // West
  { city: "Los Angeles", region: "California", regionCode: "CA", macroRegion: "west" },
  { city: "San Diego", region: "California", regionCode: "CA", macroRegion: "west" },
  { city: "San Francisco", region: "California", regionCode: "CA", macroRegion: "west" },
  { city: "San Jose", region: "California", regionCode: "CA", macroRegion: "west" },
  { city: "Sacramento", region: "California", regionCode: "CA", macroRegion: "west" },
  { city: "Fresno", region: "California", regionCode: "CA", macroRegion: "west" },
  { city: "Oakland", region: "California", regionCode: "CA", macroRegion: "west" },
  { city: "Long Beach", region: "California", regionCode: "CA", macroRegion: "west" },
  { city: "Seattle", region: "Washington", regionCode: "WA", macroRegion: "west" },
  { city: "Tacoma", region: "Washington", regionCode: "WA", macroRegion: "west" },
  { city: "Portland", region: "Oregon", regionCode: "OR", macroRegion: "west" },
  { city: "Denver", region: "Colorado", regionCode: "CO", macroRegion: "west" },
  { city: "Colorado Springs", region: "Colorado", regionCode: "CO", macroRegion: "west" },
  { city: "Salt Lake City", region: "Utah", regionCode: "UT", macroRegion: "west" },
];

// Nearby/hometown options per city (smaller towns nearby)
// Format "City, XX" — the generator expands XX to the full region name on read.
export const NEARBY_HOMETOWNS = {
  "New York": ["Yonkers, NY", "White Plains, NY", "Hoboken, NJ", "Stamford, CT", "Long Island City, NY"],
  "Brooklyn": ["Staten Island, NY", "Flatbush, NY", "Bay Ridge, NY", "Flushing, NY", "Yonkers, NY"],
  "Queens": ["Jamaica, NY", "Astoria, NY", "Flushing, NY", "Bayside, NY", "Forest Hills, NY"],
  "Buffalo": ["Cheektowaga, NY", "Tonawanda, NY", "Amherst, NY", "Lockport, NY", "Niagara Falls, NY"],
  "Philadelphia": ["Camden, NJ", "Chester, PA", "Norristown, PA", "Trenton, NJ", "Wilmington, DE"],
  "Pittsburgh": ["Bethel Park, PA", "Monroeville, PA", "Canonsburg, PA", "Aliquippa, PA", "McKeesport, PA"],
  "Boston": ["Quincy, MA", "Somerville, MA", "Brockton, MA", "Lowell, MA", "Lynn, MA"],
  "Cambridge": ["Somerville, MA", "Malden, MA", "Medford, MA", "Watertown, MA", "Arlington, MA"],
  "Providence": ["Cranston, RI", "Pawtucket, RI", "Warwick, RI", "East Providence, RI", "Woonsocket, RI"],
  "Hartford": ["New Britain, CT", "Bristol, CT", "Meriden, CT", "Waterbury, CT", "Glastonbury, CT"],
  "Newark": ["Elizabeth, NJ", "Irvington, NJ", "Bloomfield, NJ", "East Orange, NJ", "Kearny, NJ"],
  "Jersey City": ["Bayonne, NJ", "Hoboken, NJ", "Union City, NJ", "West New York, NJ", "Weehawken, NJ"],
  "Baltimore": ["Towson, MD", "Catonsville, MD", "Dundalk, MD", "Bowie, MD", "Annapolis, MD"],
  "Washington": ["Arlington, VA", "Alexandria, VA", "Silver Spring, MD", "Bethesda, MD", "Rockville, MD"],
  "Charlotte": ["Concord, NC", "Gastonia, NC", "Rock Hill, SC", "Kannapolis, NC", "Monroe, NC"],
  "Raleigh": ["Durham, NC", "Cary, NC", "Garner, NC", "Chapel Hill, NC", "Apex, NC"],
  "Atlanta": ["Marietta, GA", "Sandy Springs, GA", "Smyrna, GA", "Roswell, GA", "Decatur, GA"],
  "Savannah": ["Pooler, GA", "Richmond Hill, GA", "Statesboro, GA", "Hilton Head Island, SC", "Beaufort, SC"],
  "Miami": ["Hialeah, FL", "Coral Gables, FL", "Homestead, FL", "North Miami, FL", "Doral, FL"],
  "Orlando": ["Kissimmee, FL", "Sanford, FL", "Lakeland, FL", "Winter Park, FL", "Altamonte Springs, FL"],
  "Tampa": ["St. Petersburg, FL", "Clearwater, FL", "Brandon, FL", "Largo, FL", "Sarasota, FL"],
  "Jacksonville": ["Orange Park, FL", "St. Augustine, FL", "Fernandina Beach, FL", "Daytona Beach, FL", "Gainesville, FL"],
  "Nashville": ["Murfreesboro, TN", "Franklin, TN", "Smyrna, TN", "Hendersonville, TN", "Clarksville, TN"],
  "Memphis": ["Germantown, TN", "Bartlett, TN", "Southaven, MS", "Cordova, TN", "Collierville, TN"],
  "Louisville": ["Lexington, KY", "Jeffersonville, IN", "Clarksville, IN", "New Albany, IN", "Elizabethtown, KY"],
  "Richmond": ["Chesterfield, VA", "Henrico, VA", "Midlothian, VA", "Glen Allen, VA", "Petersburg, VA"],
  "Virginia Beach": ["Chesapeake, VA", "Norfolk, VA", "Newport News, VA", "Hampton, VA", "Suffolk, VA"],
  "Columbia": ["Lexington, SC", "Irmo, SC", "Florence, SC", "Sumter, SC", "Myrtle Beach, SC"],
  "New Orleans": ["Metairie, LA", "Kenner, LA", "Chalmette, LA", "Gretna, LA", "Harvey, LA"],
  "Birmingham": ["Hoover, AL", "Tuscaloosa, AL", "Huntsville, AL", "Bessemer, AL", "Homewood, AL"],
  "Chicago": ["Evanston, IL", "Aurora, IL", "Rockford, IL", "Joliet, IL", "Waukegan, IL"],
  "Naperville": ["Bolingbrook, IL", "Downers Grove, IL", "Elgin, IL", "Wheaton, IL", "Lisle, IL"],
  "Detroit": ["Warren, MI", "Dearborn, MI", "Livonia, MI", "Sterling Heights, MI", "Ann Arbor, MI"],
  "Grand Rapids": ["Kentwood, MI", "Wyoming, MI", "Muskegon, MI", "Battle Creek, MI", "Kalamazoo, MI"],
  "Columbus": ["Dublin, OH", "Westerville, OH", "Grove City, OH", "Gahanna, OH", "Hilliard, OH"],
  "Cleveland": ["Akron, OH", "Parma, OH", "Elyria, OH", "Lorain, OH", "Strongsville, OH"],
  "Cincinnati": ["Dayton, OH", "Covington, KY", "Florence, KY", "Middletown, OH", "Hamilton, OH"],
  "Indianapolis": ["Carmel, IN", "Fishers, IN", "Anderson, IN", "Bloomington, IN", "Greenwood, IN"],
  "Milwaukee": ["Waukesha, WI", "Kenosha, WI", "Racine, WI", "West Allis, WI", "Brookfield, WI"],
  "Madison": ["Fitchburg, WI", "Sun Prairie, WI", "Middleton, WI", "Janesville, WI", "Beloit, WI"],
  "Minneapolis": ["St. Paul, MN", "Bloomington, MN", "Plymouth, MN", "Brooklyn Park, MN", "Duluth, MN"],
  "St. Paul": ["Woodbury, MN", "Eagan, MN", "Burnsville, MN", "Eden Prairie, MN", "Mankato, MN"],
  "Kansas City": ["Independence, MO", "Overland Park, KS", "Olathe, KS", "Lee's Summit, MO", "Springfield, MO"],
  "St. Louis": ["Chesterfield, MO", "O'Fallon, MO", "Florissant, MO", "Columbia, MO", "Belleville, IL"],
  "Omaha": ["Lincoln, NE", "Bellevue, NE", "Council Bluffs, IA", "Papillion, NE", "Fremont, NE"],
  "Dallas": ["Plano, TX", "Irving, TX", "Garland, TX", "Frisco, TX", "McKinney, TX"],
  "Houston": ["Pearland, TX", "Sugar Land, TX", "League City, TX", "Pasadena, TX", "Baytown, TX"],
  "Austin": ["Round Rock, TX", "Cedar Park, TX", "Georgetown, TX", "Pflugerville, TX", "Kyle, TX"],
  "San Antonio": ["New Braunfels, TX", "Seguin, TX", "Schertz, TX", "Converse, TX", "Universal City, TX"],
  "Fort Worth": ["Arlington, TX", "Mansfield, TX", "North Richland Hills, TX", "Haltom City, TX", "Euless, TX"],
  "El Paso": ["Las Cruces, NM", "Socorro, TX", "Horizon City, TX", "Anthony, TX", "Santa Teresa, NM"],
  "Phoenix": ["Scottsdale, AZ", "Glendale, AZ", "Chandler, AZ", "Gilbert, AZ", "Tempe, AZ"],
  "Tucson": ["Marana, AZ", "Oro Valley, AZ", "Sierra Vista, AZ", "Sahuarita, AZ", "Douglas, AZ"],
  "Las Vegas": ["North Las Vegas, NV", "Summerlin, NV", "Mesquite, NV", "Boulder City, NV", "Pahrump, NV"],
  "Henderson": ["Boulder City, NV", "Pahrump, NV", "Laughlin, NV", "Kingman, AZ", "Bullhead City, AZ"],
  "Albuquerque": ["Rio Rancho, NM", "Santa Fe, NM", "Farmington, NM", "Las Cruces, NM", "Roswell, NM"],
  "Los Angeles": ["Long Beach, CA", "Pasadena, CA", "Burbank, CA", "Glendale, CA", "Santa Monica, CA"],
  "San Diego": ["Chula Vista, CA", "El Cajon, CA", "Escondido, CA", "Oceanside, CA", "San Marcos, CA"],
  "San Francisco": ["Oakland, CA", "Berkeley, CA", "Daly City, CA", "San Mateo, CA", "Fremont, CA"],
  "San Jose": ["Santa Clara, CA", "Sunnyvale, CA", "Milpitas, CA", "Cupertino, CA", "Mountain View, CA"],
  "Sacramento": ["Elk Grove, CA", "Roseville, CA", "Citrus Heights, CA", "Rancho Cordova, CA", "Folsom, CA"],
  "Fresno": ["Clovis, CA", "Visalia, CA", "Bakersfield, CA", "Modesto, CA", "Madera, CA"],
  "Oakland": ["Fremont, CA", "Hayward, CA", "Richmond, CA", "Berkeley, CA", "San Leandro, CA"],
  "Long Beach": ["Compton, CA", "Carson, CA", "Torrance, CA", "Lakewood, CA", "Norwalk, CA"],
  "Seattle": ["Bellevue, WA", "Tacoma, WA", "Renton, WA", "Kirkland, WA", "Redmond, WA"],
  "Tacoma": ["Puyallup, WA", "Lakewood, WA", "Olympia, WA", "Auburn, WA", "Federal Way, WA"],
  "Portland": ["Beaverton, OR", "Gresham, OR", "Hillsboro, OR", "Salem, OR", "Vancouver, WA"],
  "Denver": ["Aurora, CO", "Lakewood, CO", "Arvada, CO", "Westminster, CO", "Thornton, CO"],
  "Colorado Springs": ["Pueblo, CO", "Fountain, CO", "Security-Widefield, CO", "Monument, CO", "Canon City, CO"],
  "Salt Lake City": ["West Valley City, UT", "Provo, UT", "West Jordan, UT", "Orem, UT", "Sandy, UT"],
};

// regionCode → full region name (used to expand "Yonkers, NY" → "Yonkers, New York")
export const REGION_NAME_BY_CODE = Object.fromEntries(
  CITIES.map(({ regionCode, region }) => [regionCode, region]),
);
