// Italian-language profile bio templates.
// Placeholders: {firstName}, {title}, {company}, {city}, {trait1}, {trait2},
// {hobby1}, {hobby2}, {emoji1}, {emoji2}, {quote}
export const BIO_TEMPLATES = [
  "{emoji1} {trait1} | amante di {hobby1} e {hobby2}",
  "{title} di giorno, {hobby1} di sera. Anima {trait1}. {emoji1}",
  "{trait1} | sempre alla ricerca di {hobby1} {emoji1}",
  "Vivo la mia vita al meglio. Lavoro in {company}. {trait1} e fiero. {emoji1}",
  "Appassionato di {hobby1} e {hobby2}. {trait1} dentro. {emoji1}",
  "{trait1} | caffè dipendente | qui per divertirmi {emoji1}",
  "Ciao! Quando non sono in {company}, mi trovi a {hobby1}. {emoji1}",
  "{title} di mestiere. {trait1} per natura. Grande fan di {hobby1}.",
  "Lavoro sodo, gioco di più. {trait1}. Mi piace {hobby1} e {hobby2}. {emoji1}",
  "Mi godo la vita come {title}. {hobby1} è la mia terapia. {emoji1}",
  "Cose grandi ogni giorno. {trait1} {emoji1}",
  "Famiglia. Amici. {hobby1}. Mi basta questo. {emoji1}",
  "Vivere con uno scopo. {trait1} e sempre in crescita. {emoji1}",
  "Lavoro sodo ogni giorno. Adoro {hobby1}. {emoji1}",
  "Persona {trait1}. {hobby1} mi tiene in equilibrio. {emoji1}",
  "Persona semplice. Amo {hobby1}, {hobby2} e il buon cibo. {emoji1}",
  "{title} | {trait1} | sempre pronto per {hobby1} {emoji1}",
  "Costruisco una vita che amo. {trait1} e {trait2}. {emoji1}",
  "Faccio sul serio ogni giorno. {hobby1} e {hobby2} la sera. {trait1} sempre.",
  "{firstName} • {title} • {trait1} • amante di {hobby1} {emoji1}",
  "Felice e grato. Famiglia prima di tutto. {hobby1} subito dopo. {emoji1}",
  "Vivo la mia verità. {trait1} fino in fondo. {emoji1}",
  "La vita è breve — mangia bene e fai ciò che ami. {trait1} {emoji1}",
  "Inseguo i sogni un giorno alla volta. Adoro {hobby1}. {emoji1}",
  "{trait1} e senza scuse. {hobby1} è la mia vita. {emoji1}",
  "Credo nel lavoro duro e in {hobby1}. {title} | {trait1}",
  "Caffè, buone vibrazioni e {hobby1} — questa è la mia vita. {trait1}. {emoji1}",
  "{trait1}. Mi trovi quasi sempre a {hobby1}. {emoji1}",
  "Inseguo i sogni ogni giorno. {trait1} e {trait2}. Tutto quel che amo: {hobby1}.",
  "Reale, autentico, in movimento. {title} | {company} | {trait1} | {hobby1}",
  "Felice quando sono a {hobby1}. Persona {trait1} dentro e fuori. {emoji1}",
  "Amante dei cani. {trait1}. Qui per ridere. {emoji1}",
  "Non tutti quelli che vagano sono perduti. {trait1}. {emoji1}",
  "Con i piedi per terra. Amo {hobby1}, {hobby2} e i weekend lunghi. {emoji1}",
  "{trait1} di default. Forte passione per {hobby1}. {emoji1}",
  "{title}. {trait1}. Ossessionato da {hobby1}. {emoji1}",
  "Prova vivente che il lavoro paga. Appassionato di {hobby1}. {emoji1}",
  "{firstName} — {title}, {trait1}. Sempre pronto per {hobby1}.",
  "Sincero al 100%. {title}. {trait1}. Mi interesso a {hobby1} e a conversazioni vere.",
  "Grato ogni giorno. {trait1} | {hobby1} è la mia fuga. {emoji1}",
  "Persona normale, grandi sogni. {trait1}. Vivo di {hobby1} e caffè. {emoji1}",
  "{trait1} e {trait2}. Sempre alla ricerca di {hobby1}. {emoji1}",
  "Lavoro in {company}, {hobby1} dipendente. {trait1} fino al midollo.",
  "Mi piace {hobby1}. Semplice. {emoji1}",
  "{trait1} | {title} | {hobby1} | buon cibo | compagnia migliore {emoji1}",
  "Cerco di migliorarmi ogni giorno. {trait1}. {emoji1}",
  "{hobby1} mi ha cambiato la vita. {title} in {company}. {trait1} e felice.",
  "Non solo un {title} — sono anche {trait1} e mi piace {hobby1}. {emoji1}",
  "Vivo per {hobby1}. {trait1}. {emoji1}",
  "Energia {trait1}. Vieni a fare {hobby1} con me. {emoji1}",
];

// Quote-based templates (use {quote}, {emoji1}, {emoji2})
export const QUOTE_TEMPLATES = [
  '"{quote}" {emoji1} | {trait1}',
  '"{quote}" — vivo così ogni giorno. {emoji1}',
  '{emoji1} "{quote}" | {title} | {trait1}',
  '"{quote}" {emoji1}{emoji2} | amante di {hobby1}',
  'Il mio motto: "{quote}" {emoji1} | {trait1}',
  '"{quote}" {emoji1} — questo è quello che devi sapere di me.',
  '{emoji1} "{quote}" | {trait1} | sempre alla ricerca di {hobby1}',
  'Vivo seguendo "{quote}" ogni giorno. {emoji1} | {trait1}',
  '"{quote}" {emoji2} | {hobby1} è la mia terapia. {emoji1}',
  '{emoji1} "{quote}" {emoji2} | {trait1}',
];

// Italian-language Bible quotes (or universal proverbs)
export const QUOTES = [
  "Posso tutto in Colui che mi dà forza. — Fil 4,13",
  "Il Signore è il mio pastore: non manco di nulla. — Salmo 23,1",
  "Confida nel Signore con tutto il cuore. — Proverbi 3,5",
  "Sii forte e coraggioso. Non temere. — Giosuè 1,9",
  "Dio ha tanto amato il mondo. — Giovanni 3,16",
  "L'amore è paziente, l'amore è benevolo. — 1 Cor 13,4",
  "Gettate in lui ogni vostra preoccupazione. — 1 Pietro 5,7",
  "Il Signore è con te ovunque tu vada. — Giosuè 1,9",
  "In ogni circostanza rendete grazie. — 1 Tess 5,18",
  "A Dio tutto è possibile. — Matteo 19,26",
  "Fermatevi e sappiate che io sono Dio. — Salmo 46,10",
  "Cercate prima il regno di Dio. — Matteo 6,33",
  "Camminate per fede e non per visione. — 2 Cor 5,7",
  "La gioia del Signore è la vostra forza. — Neemia 8,10",
  "Egli dà forza allo stanco. — Isaia 40,29",
  "La tua parola è lampada per i miei passi. — Salmo 119,105",
  "Tutto ciò che fate, fatelo con amore. — 1 Cor 16,14",
  "Beati i puri di cuore. — Mt 5,8",
  "Non conformatevi alla mentalità di questo mondo. — Romani 12,2",
  "La verità vi farà liberi. — Giovanni 8,32",
  "Siate sempre lieti. — 1 Tess 5,16",
  "Chiedete e vi sarà dato. — Matteo 7,7",
  "Ti basta la mia grazia. — 2 Cor 12,9",
  "Non temere, io sono con te. — Isaia 41,10",
  "Dio è per noi rifugio e forza. — Salmo 46,1",
  "Risplenda la vostra luce davanti agli uomini. — Matteo 5,16",
  "Perdonate come il Signore vi ha perdonato. — Colossesi 3,13",
  "Un cuore lieto è una buona medicina. — Proverbi 17,22",
  "Progetti di pace e non di sventura. — Ger 29,11",
  "La fede è fondamento delle cose che si sperano. — Eb 11,1",
  "Ama il prossimo tuo come te stesso. — Marco 12,31",
  "Affida al Signore le tue opere. — Proverbi 16,3",
  "Risana i cuori affranti. — Salmo 147,3",
  "Chi spera nel Signore riacquista forza. — Isaia 40,31",
  "Non angustiatevi per nulla. — Filippesi 4,6",
  "Il ferro si lima col ferro. — Proverbi 27,17",
  "Custodisci il tuo cuore con ogni cura. — Proverbi 4,23",
  "Trova la tua gioia nel Signore. — Salmo 37,4",
  "La pace di Cristo regni nei vostri cuori. — Col 3,15",
  "Qualunque cosa facciate, fatela di cuore. — Col 3,23",
  "Ti loderò, Signore, con tutto il cuore. — Salmo 9,1",
  "Il Signore è vicino a chi ha il cuore ferito. — Salmo 34,18",
  "Più grande è colui che è in voi. — 1 Gv 4,4",
  "Nessuna arma forgiata contro di me prevarrà. — Isaia 54,17",
  "Questo è il giorno fatto dal Signore: rallegriamoci. — Salmo 118,24",
  "Siate benevoli gli uni verso gli altri. — Efesini 4,32",
  "Umiliatevi davanti al Signore. — Giacomo 4,10",
  "Avvicinatevi a Dio e lui si avvicinerà a voi. — Giacomo 4,8",
  "Non stanchiamoci di fare il bene. — Galati 6,9",
  "È risorto. — Matteo 28,6",
];

// Italian motivational quotes — short, shareable
export const MOTIVATIONAL_QUOTES = [
  "Sii l'energia che vuoi attrarre",
  "Fallo con passione o non farlo",
  "Resta umile, lavora sodo, sii gentile",
  "Le cose belle richiedono tempo",
  "Insegui la visione, non il denaro",
  "Cresci attraverso ciò che attraversi",
  "Meno parole, più azione",
  "Falla accadere",
  "La tua energia attira la tua tribù",
  "Guadagnatelo ogni giorno",
  "Sii una voce, non un'eco",
  "Vivi semplicemente, ama profondamente",
  "Lavora in silenzio, lascia che sia il successo a fare rumore",
  "Un giorno alla volta",
  "Fai di più di ciò che ti rende felice",
  "La vita è breve, rendila dolce",
  "Resta concentrato e non mollare mai",
  "Colleziona momenti, non cose",
  "Sogna in grande, lavora sodo, resta umile",
  "Sii il cambiamento che vuoi vedere",
  "Non tutti quelli che vagano sono perduti",
  "Ogni giorno è una seconda occasione",
  "Sii te stesso, gli altri sono già presi",
  "Se ti fa paura, forse vale la pena",
  "Fai del bene e il bene tornerà",
  "Attiri ciò che sei",
  "Continua, sei più vicino di quanto credi",
  "Progressi, non perfezione",
  "Abbi pazienza e fidati del percorso",
  "Fai ciò che ami, ama ciò che fai",
  "La vista migliore arriva dopo la salita più dura",
  "Il lavoro duro batte il talento quando il talento non si impegna",
  "Rendi importante questo giorno",
  "Sii gentile, sii grato, sii umile",
  "Piccoli passi ogni giorno",
  "Vivi senza rimpianti",
  "Circondati di persone giuste",
  "Diventi ciò in cui credi",
  "Fai brillare la tua luce",
  "Grato per ogni mattino",
  "Scegli la gioia",
  "Sii paziente con te stesso",
  "Respira. Ce la fai",
  "Non smettere mai di imparare",
  "Fallo con paura",
  "Fede oltre la paura",
  "I fatti contano più delle parole",
  "Semplifica",
  "Ama ciò che hai mentre lavori per ciò che vuoi",
];

// Safe emojis for bio use — same set works cross-locale
export const BIO_EMOJIS = [
  "✨", "🌿", "☕", "🎯", "💫", "🌊", "🔥", "🙌", "💡", "🌱",
  "🎶", "🏔️", "🌸", "⚡", "🌍", "🎨", "📚", "🏋️", "🤝", "💪",
  "🌅", "🐾", "🍀", "🎸", "🚀", "🌙", "🦋", "🌻", "🍃", "💙",
];

// Italian traits — kept as noun-style phrases so they slot into any template
// without gender-agreement headaches.
export const TRAITS = [
  "amante dell'avventura",
  "famiglia al primo posto",
  "appassionato di fitness",
  "amante dei cani",
  "caffè dipendente",
  "voglia di viaggiare",
  "creativo",
  "rilassato",
  "gran lavoratore",
  "ottimista",
  "con i piedi per terra",
  "ambizioso",
  "amante della natura",
  "attento alla comunità",
  "uomo di fede",
  "appassionato di cucina",
  "appassionato di musica",
  "tifoso sportivo",
  "tech enthusiast",
  "amante della natura",
  "concreto e determinato",
  "mentalità positiva",
  "ama la gente",
  "amante degli animali",
  "lettore accanito",
  "scaltro e pratico",
  "auto-motivato",
  "grato",
  "spontaneo",
  "attento ai dettagli",
  "grande cuore",
  "determinato",
  "spirito libero",
  "senza fronzoli",
  "riflessivo",
  "appassionato",
  "umile",
  "autentico",
  "divertente",
  "curioso",
];
