// Each city entry: { city, region, regionCode, macroRegion }
// region   = Italian regione name (full, e.g. "Lombardia")
// regionCode = short code used to key high schools
// macroRegion = nord | centro | sud (used to key universities)
export const CITIES = [
  // Nord
  { city: "Milano", region: "Lombardia", regionCode: "LOM", macroRegion: "nord" },
  { city: "Bergamo", region: "Lombardia", regionCode: "LOM", macroRegion: "nord" },
  { city: "Brescia", region: "Lombardia", regionCode: "LOM", macroRegion: "nord" },
  { city: "Como", region: "Lombardia", regionCode: "LOM", macroRegion: "nord" },
  { city: "Monza", region: "Lombardia", regionCode: "LOM", macroRegion: "nord" },
  { city: "Torino", region: "Piemonte", regionCode: "PIE", macroRegion: "nord" },
  { city: "Novara", region: "Piemonte", regionCode: "PIE", macroRegion: "nord" },
  { city: "Alessandria", region: "Piemonte", regionCode: "PIE", macroRegion: "nord" },
  { city: "Genova", region: "Liguria", regionCode: "LIG", macroRegion: "nord" },
  { city: "La Spezia", region: "Liguria", regionCode: "LIG", macroRegion: "nord" },
  { city: "Savona", region: "Liguria", regionCode: "LIG", macroRegion: "nord" },
  { city: "Bologna", region: "Emilia-Romagna", regionCode: "EMR", macroRegion: "nord" },
  { city: "Modena", region: "Emilia-Romagna", regionCode: "EMR", macroRegion: "nord" },
  { city: "Parma", region: "Emilia-Romagna", regionCode: "EMR", macroRegion: "nord" },
  { city: "Reggio Emilia", region: "Emilia-Romagna", regionCode: "EMR", macroRegion: "nord" },
  { city: "Rimini", region: "Emilia-Romagna", regionCode: "EMR", macroRegion: "nord" },
  { city: "Ferrara", region: "Emilia-Romagna", regionCode: "EMR", macroRegion: "nord" },
  { city: "Venezia", region: "Veneto", regionCode: "VEN", macroRegion: "nord" },
  { city: "Verona", region: "Veneto", regionCode: "VEN", macroRegion: "nord" },
  { city: "Padova", region: "Veneto", regionCode: "VEN", macroRegion: "nord" },
  { city: "Vicenza", region: "Veneto", regionCode: "VEN", macroRegion: "nord" },
  { city: "Treviso", region: "Veneto", regionCode: "VEN", macroRegion: "nord" },
  { city: "Trieste", region: "Friuli-Venezia Giulia", regionCode: "FVG", macroRegion: "nord" },
  { city: "Udine", region: "Friuli-Venezia Giulia", regionCode: "FVG", macroRegion: "nord" },
  { city: "Trento", region: "Trentino-Alto Adige", regionCode: "TAA", macroRegion: "nord" },
  { city: "Bolzano", region: "Trentino-Alto Adige", regionCode: "TAA", macroRegion: "nord" },
  // Centro
  { city: "Roma", region: "Lazio", regionCode: "LAZ", macroRegion: "centro" },
  { city: "Latina", region: "Lazio", regionCode: "LAZ", macroRegion: "centro" },
  { city: "Frosinone", region: "Lazio", regionCode: "LAZ", macroRegion: "centro" },
  { city: "Viterbo", region: "Lazio", regionCode: "LAZ", macroRegion: "centro" },
  { city: "Firenze", region: "Toscana", regionCode: "TOS", macroRegion: "centro" },
  { city: "Pisa", region: "Toscana", regionCode: "TOS", macroRegion: "centro" },
  { city: "Siena", region: "Toscana", regionCode: "TOS", macroRegion: "centro" },
  { city: "Livorno", region: "Toscana", regionCode: "TOS", macroRegion: "centro" },
  { city: "Lucca", region: "Toscana", regionCode: "TOS", macroRegion: "centro" },
  { city: "Perugia", region: "Umbria", regionCode: "UMB", macroRegion: "centro" },
  { city: "Terni", region: "Umbria", regionCode: "UMB", macroRegion: "centro" },
  { city: "Ancona", region: "Marche", regionCode: "MAR", macroRegion: "centro" },
  { city: "Pesaro", region: "Marche", regionCode: "MAR", macroRegion: "centro" },
  { city: "Pescara", region: "Abruzzo", regionCode: "ABR", macroRegion: "centro" },
  { city: "L'Aquila", region: "Abruzzo", regionCode: "ABR", macroRegion: "centro" },
  { city: "Teramo", region: "Abruzzo", regionCode: "ABR", macroRegion: "centro" },
  // Sud
  { city: "Napoli", region: "Campania", regionCode: "CAM", macroRegion: "sud" },
  { city: "Salerno", region: "Campania", regionCode: "CAM", macroRegion: "sud" },
  { city: "Caserta", region: "Campania", regionCode: "CAM", macroRegion: "sud" },
  { city: "Bari", region: "Puglia", regionCode: "PUG", macroRegion: "sud" },
  { city: "Lecce", region: "Puglia", regionCode: "PUG", macroRegion: "sud" },
  { city: "Taranto", region: "Puglia", regionCode: "PUG", macroRegion: "sud" },
  { city: "Foggia", region: "Puglia", regionCode: "PUG", macroRegion: "sud" },
  { city: "Brindisi", region: "Puglia", regionCode: "PUG", macroRegion: "sud" },
  { city: "Palermo", region: "Sicilia", regionCode: "SIC", macroRegion: "sud" },
  { city: "Catania", region: "Sicilia", regionCode: "SIC", macroRegion: "sud" },
  { city: "Messina", region: "Sicilia", regionCode: "SIC", macroRegion: "sud" },
  { city: "Siracusa", region: "Sicilia", regionCode: "SIC", macroRegion: "sud" },
  { city: "Trapani", region: "Sicilia", regionCode: "SIC", macroRegion: "sud" },
  { city: "Cagliari", region: "Sardegna", regionCode: "SAR", macroRegion: "sud" },
  { city: "Sassari", region: "Sardegna", regionCode: "SAR", macroRegion: "sud" },
  { city: "Olbia", region: "Sardegna", regionCode: "SAR", macroRegion: "sud" },
  { city: "Catanzaro", region: "Calabria", regionCode: "CAL", macroRegion: "sud" },
  { city: "Cosenza", region: "Calabria", regionCode: "CAL", macroRegion: "sud" },
  { city: "Reggio Calabria", region: "Calabria", regionCode: "CAL", macroRegion: "sud" },
  { city: "Potenza", region: "Basilicata", regionCode: "BAS", macroRegion: "sud" },
  { city: "Matera", region: "Basilicata", regionCode: "BAS", macroRegion: "sud" },
];

// Nearby/hometown options per city — Italian provinces and nearby comuni.
// Italian hometowns use full region names directly, so the generator's
// regionCode-expansion regex is a no-op for these labels.
export const NEARBY_HOMETOWNS = {
  "Milano": ["Sesto San Giovanni, Lombardia", "Cinisello Balsamo, Lombardia", "Cologno Monzese, Lombardia", "Rho, Lombardia", "Legnano, Lombardia"],
  "Bergamo": ["Treviglio, Lombardia", "Seriate, Lombardia", "Dalmine, Lombardia", "Albino, Lombardia", "Ponte San Pietro, Lombardia"],
  "Brescia": ["Desenzano del Garda, Lombardia", "Montichiari, Lombardia", "Rovato, Lombardia", "Palazzolo sull'Oglio, Lombardia"],
  "Como": ["Cantù, Lombardia", "Mariano Comense, Lombardia", "Erba, Lombardia", "Lecco, Lombardia"],
  "Monza": ["Brugherio, Lombardia", "Lissone, Lombardia", "Desio, Lombardia", "Seregno, Lombardia"],
  "Torino": ["Moncalieri, Piemonte", "Rivoli, Piemonte", "Collegno, Piemonte", "Settimo Torinese, Piemonte", "Nichelino, Piemonte"],
  "Novara": ["Borgomanero, Piemonte", "Trecate, Piemonte", "Galliate, Piemonte"],
  "Alessandria": ["Casale Monferrato, Piemonte", "Novi Ligure, Piemonte", "Tortona, Piemonte"],
  "Genova": ["Sestri Levante, Liguria", "Rapallo, Liguria", "Chiavari, Liguria", "Recco, Liguria"],
  "La Spezia": ["Sarzana, Liguria", "Lerici, Liguria", "Portovenere, Liguria"],
  "Savona": ["Albenga, Liguria", "Finale Ligure, Liguria", "Loano, Liguria"],
  "Bologna": ["Imola, Emilia-Romagna", "Casalecchio di Reno, Emilia-Romagna", "San Lazzaro di Savena, Emilia-Romagna"],
  "Modena": ["Carpi, Emilia-Romagna", "Sassuolo, Emilia-Romagna", "Mirandola, Emilia-Romagna"],
  "Parma": ["Fidenza, Emilia-Romagna", "Salsomaggiore Terme, Emilia-Romagna", "Collecchio, Emilia-Romagna"],
  "Reggio Emilia": ["Scandiano, Emilia-Romagna", "Correggio, Emilia-Romagna", "Casalgrande, Emilia-Romagna"],
  "Rimini": ["Riccione, Emilia-Romagna", "Cattolica, Emilia-Romagna", "Santarcangelo di Romagna, Emilia-Romagna"],
  "Ferrara": ["Cento, Emilia-Romagna", "Comacchio, Emilia-Romagna", "Argenta, Emilia-Romagna"],
  "Venezia": ["Mestre, Veneto", "Marghera, Veneto", "Chioggia, Veneto", "Mira, Veneto"],
  "Verona": ["Villafranca di Verona, Veneto", "Legnago, Veneto", "San Bonifacio, Veneto"],
  "Padova": ["Abano Terme, Veneto", "Selvazzano Dentro, Veneto", "Cittadella, Veneto"],
  "Vicenza": ["Bassano del Grappa, Veneto", "Schio, Veneto", "Thiene, Veneto"],
  "Treviso": ["Conegliano, Veneto", "Castelfranco Veneto, Veneto", "Mogliano Veneto, Veneto"],
  "Trieste": ["Muggia, Friuli-Venezia Giulia", "Duino-Aurisina, Friuli-Venezia Giulia"],
  "Udine": ["Codroipo, Friuli-Venezia Giulia", "Cividale del Friuli, Friuli-Venezia Giulia", "Pordenone, Friuli-Venezia Giulia"],
  "Trento": ["Rovereto, Trentino-Alto Adige", "Riva del Garda, Trentino-Alto Adige", "Pergine Valsugana, Trentino-Alto Adige"],
  "Bolzano": ["Merano, Trentino-Alto Adige", "Bressanone, Trentino-Alto Adige", "Brunico, Trentino-Alto Adige"],
  "Roma": ["Fiumicino, Lazio", "Tivoli, Lazio", "Pomezia, Lazio", "Guidonia Montecelio, Lazio", "Velletri, Lazio"],
  "Latina": ["Aprilia, Lazio", "Terracina, Lazio", "Sezze, Lazio", "Cisterna di Latina, Lazio"],
  "Frosinone": ["Cassino, Lazio", "Sora, Lazio", "Anagni, Lazio"],
  "Viterbo": ["Civita Castellana, Lazio", "Tarquinia, Lazio", "Montefiascone, Lazio"],
  "Firenze": ["Scandicci, Toscana", "Sesto Fiorentino, Toscana", "Empoli, Toscana", "Prato, Toscana"],
  "Pisa": ["Cascina, Toscana", "Pontedera, Toscana", "San Giuliano Terme, Toscana"],
  "Siena": ["Poggibonsi, Toscana", "Colle di Val d'Elsa, Toscana", "Montepulciano, Toscana"],
  "Livorno": ["Piombino, Toscana", "Cecina, Toscana", "Rosignano Marittimo, Toscana"],
  "Lucca": ["Viareggio, Toscana", "Capannori, Toscana", "Camaiore, Toscana"],
  "Perugia": ["Foligno, Umbria", "Città di Castello, Umbria", "Spoleto, Umbria", "Assisi, Umbria"],
  "Terni": ["Narni, Umbria", "Orvieto, Umbria", "Amelia, Umbria"],
  "Ancona": ["Senigallia, Marche", "Jesi, Marche", "Falconara Marittima, Marche", "Osimo, Marche"],
  "Pesaro": ["Fano, Marche", "Urbino, Marche", "Mondolfo, Marche"],
  "Pescara": ["Montesilvano, Abruzzo", "Chieti, Abruzzo", "Spoltore, Abruzzo"],
  "L'Aquila": ["Avezzano, Abruzzo", "Sulmona, Abruzzo", "Celano, Abruzzo"],
  "Teramo": ["Giulianova, Abruzzo", "Roseto degli Abruzzi, Abruzzo", "Atri, Abruzzo"],
  "Napoli": ["Pozzuoli, Campania", "Casoria, Campania", "Giugliano in Campania, Campania", "Portici, Campania", "Castellammare di Stabia, Campania"],
  "Salerno": ["Cava de' Tirreni, Campania", "Battipaglia, Campania", "Nocera Inferiore, Campania", "Pagani, Campania"],
  "Caserta": ["Aversa, Campania", "Marcianise, Campania", "Maddaloni, Campania", "Santa Maria Capua Vetere, Campania"],
  "Bari": ["Altamura, Puglia", "Molfetta, Puglia", "Bitonto, Puglia", "Monopoli, Puglia"],
  "Lecce": ["Nardò, Puglia", "Galatina, Puglia", "Copertino, Puglia", "Gallipoli, Puglia"],
  "Taranto": ["Martina Franca, Puglia", "Grottaglie, Puglia", "Manduria, Puglia"],
  "Foggia": ["Cerignola, Puglia", "Manfredonia, Puglia", "San Severo, Puglia"],
  "Brindisi": ["Ostuni, Puglia", "Francavilla Fontana, Puglia", "Mesagne, Puglia"],
  "Palermo": ["Bagheria, Sicilia", "Monreale, Sicilia", "Carini, Sicilia", "Termini Imerese, Sicilia"],
  "Catania": ["Acireale, Sicilia", "Misterbianco, Sicilia", "Paternò, Sicilia", "Gravina di Catania, Sicilia"],
  "Messina": ["Milazzo, Sicilia", "Barcellona Pozzo di Gotto, Sicilia", "Taormina, Sicilia"],
  "Siracusa": ["Augusta, Sicilia", "Avola, Sicilia", "Noto, Sicilia"],
  "Trapani": ["Marsala, Sicilia", "Mazara del Vallo, Sicilia", "Alcamo, Sicilia"],
  "Cagliari": ["Quartu Sant'Elena, Sardegna", "Selargius, Sardegna", "Assemini, Sardegna", "Sestu, Sardegna"],
  "Sassari": ["Alghero, Sardegna", "Porto Torres, Sardegna", "Ozieri, Sardegna"],
  "Olbia": ["Tempio Pausania, Sardegna", "Arzachena, Sardegna", "La Maddalena, Sardegna"],
  "Catanzaro": ["Soverato, Calabria", "Lamezia Terme, Calabria", "Sellia Marina, Calabria"],
  "Cosenza": ["Rende, Calabria", "Castrovillari, Calabria", "Paola, Calabria"],
  "Reggio Calabria": ["Gioia Tauro, Calabria", "Palmi, Calabria", "Locri, Calabria"],
  "Potenza": ["Melfi, Basilicata", "Lavello, Basilicata", "Avigliano, Basilicata"],
  "Matera": ["Pisticci, Basilicata", "Policoro, Basilicata", "Bernalda, Basilicata"],
};

// Italian hometown labels already include the full region name, so this map
// stays empty — the generator's regionCode-expansion regex won't match anything
// that doesn't end in a 2–3-letter code.
export const REGION_NAME_BY_CODE = {};
