// Shared international travel destinations — used by all countries.
// Each entry: { place }. Dates are stamped at generation time.
export const INTL_DESTINATIONS = [
  { place: "Paris, France" },
  { place: "London, England" },
  { place: "Rome, Italy" },
  { place: "Barcelona, Spain" },
  { place: "Amsterdam, Netherlands" },
  { place: "Berlin, Germany" },
  { place: "Prague, Czech Republic" },
  { place: "Vienna, Austria" },
  { place: "Lisbon, Portugal" },
  { place: "Athens, Greece" },
  { place: "Budapest, Hungary" },
  { place: "Copenhagen, Denmark" },
  { place: "Stockholm, Sweden" },
  { place: "Dublin, Ireland" },
  { place: "Brussels, Belgium" },
  { place: "Zurich, Switzerland" },
  { place: "Milan, Italy" },
  { place: "Venice, Italy" },
  { place: "Florence, Italy" },
  { place: "Madrid, Spain" },
  { place: "Seville, Spain" },
  { place: "Dubrovnik, Croatia" },
  { place: "Edinburgh, Scotland" },
  { place: "Munich, Germany" },
  { place: "Hamburg, Germany" },
  { place: "Warsaw, Poland" },
  { place: "Krakow, Poland" },
  { place: "Reykjavik, Iceland" },
  { place: "Santorini, Greece" },
  { place: "Porto, Portugal" },
  { place: "Bruges, Belgium" },
  { place: "Nice, France" },
  { place: "Marseille, France" },
  { place: "Oslo, Norway" },
  { place: "Helsinki, Finland" },
  { place: "Tallinn, Estonia" },
  { place: "Riga, Latvia" },
  { place: "Ljubljana, Slovenia" },
  { place: "Valletta, Malta" },
  { place: "Palermo, Italy" },
];
