// 50 American-style bio templates
// Placeholders: {firstName}, {title}, {company}, {trait1}, {trait2}, {hobby1}, {hobby2}, {emoji1}, {emoji2}
export const BIO_TEMPLATES = [
  "{emoji1} {trait1} | lover of {hobby1} and {hobby2}",
  "{title} by day, {hobby1} enthusiast by night. {trait1} soul. {emoji1}",
  "{trait1} | Always chasing {hobby1} {emoji1}",
  "Living my best life! Working at {company}. {trait1} and proud. {emoji1}",
  "Passionate about {hobby1} and {hobby2}. {trait1} individual. {emoji1}",
  "{trait1} | Coffee addict | Here for a good time {emoji1}",
  "Hey there! When I'm not at {company}, you'll find me {hobby1}. {emoji1}",
  "{title} by trade. {trait1} by nature. Big fan of {hobby1}.",
  "Work hard, play harder. {trait1}. Into {hobby1} and {hobby2}. {emoji1}",
  "Loving life as a {title}. {hobby1} is my therapy. {emoji1}",
  "Doing big things every day. {trait1} {emoji1}",
  "God. Family. {hobby1}. That's all I need. {emoji1}",
  "Living life with purpose. {trait1} and always growing. {emoji1}",
  "Working hard every day. Love {hobby1}. {emoji1}",
  "{trait1} human being. {hobby1} keeps me sane. {emoji1}",
  "Simple person. Love {hobby1}, {hobby2}, and good food. {emoji1}",
  "{title} | {trait1} | always down for {hobby1} {emoji1}",
  "Building a life I love. {trait1} and {trait2}. {emoji1}",
  "Making moves every day. {hobby1} and {hobby2} by night. {trait1} always.",
  "{firstName} • {title} • {trait1} • {hobby1} lover {emoji1}",
  "Blessed and grateful. Family first. {hobby1} second. {emoji1}",
  "Just here living my truth. {trait1} through and through. {emoji1}",
  "Life is short — eat good food and do what you love. {trait1} {emoji1}",
  "Working toward my dreams one day at a time. Love {hobby1}. {emoji1}",
  "{trait1} and unapologetically me. {hobby1} is life. {emoji1}",
  "I believe in hard work and {hobby1}. {title} | {trait1}",
  "Coffee, good vibes, and {hobby1} — that's my life. {trait1}. {emoji1}",
  "{trait1}. You'll usually find me {hobby1}. {emoji1}",
  "Chasing dreams every day. {trait1} and {trait2}. All about that {hobby1} life.",
  "Keep it real, keep it moving. {title} | {company} | {trait1} | {hobby1}",
  "Happiest when I'm {hobby1}. {trait1} person through and through. {emoji1}",
  "Dog lover. {trait1}. Here for a good laugh. {emoji1}",
  "Not all those who wander are lost. {trait1}. {emoji1}",
  "Down to earth. Love {hobby1}, {hobby2}, and long weekends. {emoji1}",
  "{trait1} by default. Big into {hobby1}. {emoji1}",
  "{title}. {trait1}. Obsessed with {hobby1}. {emoji1}",
  "Living proof that hard work pays off. {hobby1} enthusiast. {emoji1}",
  "{firstName} — {title}, {trait1}. Always up for {hobby1}.",
  "Keeping it 100. {title}. {trait1}. Into {hobby1} and real conversations.",
  "Grateful for every day. {trait1} | {hobby1} is my escape. {emoji1}",
  "Regular person, big dreams. {trait1}. I run on {hobby1} and coffee. {emoji1}",
  "{trait1} and {trait2}. Forever chasing {hobby1}. {emoji1}",
  "Employed at {company}, {hobby1} obsessed. {trait1} to the core.",
  "I love {hobby1}. Pretty simple. {emoji1}",
  "{trait1} | {title} | {hobby1} | good food | better company {emoji1}",
  "Trying to be a better version of myself every day. {trait1}. {emoji1}",
  "{hobby1} changed my life. {title} at {company}. {trait1} and loving it.",
  "Not just a {title} — I'm also {trait1} and really into {hobby1}. {emoji1}",
  "Living for {hobby1}. {trait1}. {emoji1}",
  "{trait1} energy only. Come {hobby1} with me sometime. {emoji1}",
];

// Quote-based templates (use {quote}, {emoji1}, {emoji2})
export const QUOTE_TEMPLATES = [
  '"{quote}" {emoji1} | {trait1}',
  '"{quote}" — living by this every day. {emoji1}',
  '{emoji1} "{quote}" | {title} | {trait1}',
  '"{quote}" {emoji1}{emoji2} | {hobby1} lover',
  'My motto: "{quote}" {emoji1} | {trait1}',
  '"{quote}" {emoji1} — that\'s all you need to know about me.',
  '{emoji1} "{quote}" | {trait1} | always chasing {hobby1}',
  'Living by "{quote}" every single day. {emoji1} | {trait1}',
  '"{quote}" {emoji2} | {hobby1} is my therapy. {emoji1}',
  '{emoji1} "{quote}" {emoji2} | {trait1}',
];

// 50 Bible quotes
export const QUOTES = [
  "I can do all things through Christ who strengthens me. — Phil 4:13",
  "The Lord is my shepherd; I shall not want. — Psalm 23:1",
  "Trust in the Lord with all your heart. — Proverbs 3:5",
  "Be strong and courageous. Do not be afraid. — Joshua 1:9",
  "For God so loved the world. — John 3:16",
  "Love is patient, love is kind. — 1 Cor 13:4",
  "Cast all your anxiety on him because he cares for you. — 1 Peter 5:7",
  "The Lord your God is with you wherever you go. — Joshua 1:9",
  "Give thanks in all circumstances. — 1 Thess 5:18",
  "With God all things are possible. — Matthew 19:26",
  "Be still and know that I am God. — Psalm 46:10",
  "Seek first the kingdom of God. — Matthew 6:33",
  "Walk by faith, not by sight. — 2 Cor 5:7",
  "The joy of the Lord is your strength. — Nehemiah 8:10",
  "He gives strength to the weary. — Isaiah 40:29",
  "Your word is a lamp to my feet and a light to my path. — Psalm 119:105",
  "Let all that you do be done in love. — 1 Cor 16:14",
  "Blessed are the pure in heart, for they shall see God. — Matt 5:8",
  "Do not conform to the pattern of this world. — Romans 12:2",
  "The truth will set you free. — John 8:32",
  "Rejoice always. — 1 Thess 5:16",
  "Ask and it will be given to you. — Matthew 7:7",
  "My grace is sufficient for you. — 2 Cor 12:9",
  "Fear not, for I am with you. — Isaiah 41:10",
  "God is our refuge and strength. — Psalm 46:1",
  "Let your light shine before others. — Matthew 5:16",
  "Forgive as the Lord has forgiven you. — Colossians 3:13",
  "A joyful heart is good medicine. — Proverbs 17:22",
  "Plans to prosper you and not to harm you. — Jer 29:11",
  "Now faith is confidence in what we hope for. — Hebrews 11:1",
  "Love your neighbor as yourself. — Mark 12:31",
  "Commit your work to the Lord. — Proverbs 16:3",
  "He heals the brokenhearted. — Psalm 147:3",
  "Those who hope in the Lord will renew their strength. — Isaiah 40:31",
  "Do not be anxious about anything. — Philippians 4:6",
  "As iron sharpens iron, so one person sharpens another. — Proverbs 27:17",
  "Guard your heart above all else. — Proverbs 4:23",
  "Delight yourself in the Lord. — Psalm 37:4",
  "Let the peace of Christ rule in your hearts. — Colossians 3:15",
  "Whatever you do, work at it with all your heart. — Colossians 3:23",
  "I will praise you, Lord, with all my heart. — Psalm 9:1",
  "The Lord is close to the brokenhearted. — Psalm 34:18",
  "Greater is he that is in you. — 1 John 4:4",
  "No weapon formed against me shall prosper. — Isaiah 54:17",
  "This is the day the Lord has made; let us rejoice. — Psalm 118:24",
  "Be kind and compassionate to one another. — Ephesians 4:32",
  "Humble yourselves before the Lord, and he will lift you up. — James 4:10",
  "Draw near to God and he will draw near to you. — James 4:8",
  "Do not grow weary in doing good. — Galatians 6:9",
  "He is risen. — Matthew 28:6",
];

// 50 everyday motivational quotes
export const MOTIVATIONAL_QUOTES = [
  "Be the energy you want to attract",
  "Do it with passion or not at all",
  "Stay humble, work hard, be kind",
  "Good things take time",
  "Chase the vision, not the money",
  "Grow through what you go through",
  "Less talk, more action",
  "Make it happen",
  "Your vibe attracts your tribe",
  "Earn it every day",
  "Be a voice, not an echo",
  "Live simply, love deeply",
  "Work in silence, let success make the noise",
  "One day at a time",
  "Do more of what makes you happy",
  "Life is short, make it sweet",
  "Stay focused and never give up",
  "Collect moments, not things",
  "Dream big, work hard, stay humble",
  "Be the change you wish to see",
  "Not all who wander are lost",
  "Every day is a second chance",
  "Be yourself, everyone else is taken",
  "If it scares you, it might be worth it",
  "Do good and good will come to you",
  "You attract what you are",
  "Keep going, you're closer than you think",
  "Progress, not perfection",
  "Stay patient and trust the journey",
  "Do what you love and love what you do",
  "The best view comes after the hardest climb",
  "Hard work beats talent when talent doesn't work hard",
  "Make today count",
  "Be kind, be grateful, be humble",
  "Small steps every day",
  "Blessed and highly favored",
  "Live with no regrets",
  "Surround yourself with good people",
  "You become what you believe",
  "Shine your light",
  "Grateful for every morning",
  "Choose joy",
  "Be patient with yourself",
  "Breathe. You've got this",
  "Never stop learning",
  "Do it afraid",
  "Faith over fear",
  "Actions speak louder than words",
  "Keep it simple",
  "Love what you have while working for what you want",
];

// Safe single emojis for bio use
export const BIO_EMOJIS = [
  "✨", "🌿", "☕", "🎯", "💫", "🌊", "🔥", "🙌", "💡", "🌱",
  "🎶", "🏔️", "🌸", "⚡", "🌍", "🎨", "📚", "🏋️", "🤝", "💪",
  "🌅", "🐾", "🍀", "🎸", "🚀", "🌙", "🦋", "🌻", "🍃", "💙",
];

// Trait phrases (used as {trait1} and {trait2})
export const TRAITS = [
  "adventurous",
  "family-oriented",
  "fitness-driven",
  "dog-obsessed",
  "coffee-addicted",
  "travel-hungry",
  "creative",
  "laid-back",
  "hardworking",
  "optimistic",
  "down-to-earth",
  "ambitious",
  "outdoorsy",
  "community-focused",
  "faith-driven",
  "food-obsessed",
  "music-loving",
  "sports-crazy",
  "tech-savvy",
  "nature-loving",
  "goal-getter",
  "positive-minded",
  "people-loving",
  "animal-loving",
  "book-smart",
  "street-smart",
  "self-motivated",
  "grateful",
  "spontaneous",
  "detail-oriented",
  "big-hearted",
  "driven",
  "free-spirited",
  "no-nonsense",
  "thoughtful",
  "passionate",
  "humble",
  "real",
  "funny",
  "curious",
];
