// High schools by state (used when city/state is known)
export const HIGH_SCHOOLS_BY_STATE = {
  NY: [
    "Brooklyn Technical High School", "Stuyvesant High School", "Bronx Science High School",
    "Francis Lewis High School", "Jamaica High School", "John Adams High School",
    "Erasmus Hall High School", "New Utrecht High School", "Lafayette High School",
  ],
  PA: [
    "Northeast High School", "Abraham Lincoln High School", "Simon Gratz High School",
    "Central High School", "South Philadelphia High School", "Penn Hills High School",
    "Bethel Park High School", "Upper Saint Clair High School",
  ],
  MA: [
    "Boston Latin School", "Madison Park Technical Vocational High School",
    "Cambridge Rindge and Latin School", "Newton North High School",
    "Brookline High School", "Quincy High School", "Malden High School",
  ],
  RI: ["Classical High School", "Mount Pleasant High School", "Central High School Providence", "Pilgrim High School"],
  CT: ["Hartford Public High School", "Weaver High School", "Bulkeley High School", "New Britain High School"],
  NJ: ["Weequahic High School", "West Side High School Newark", "Hudson Catholic High School", "St. Peter's Prep"],
  MD: ["Baltimore City College", "Polytechnic Institute Baltimore", "Towson High School", "Dulaney High School"],
  DC: ["Dunbar High School DC", "Woodrow Wilson High School DC", "McKinley Technical High School"],
  NC: ["Myers Park High School", "South Mecklenburg High School", "Riverside High School NC", "Millbrook High School"],
  GA: ["Grady High School", "Lakeside High School Atlanta", "Dunwoody High School", "Wheeler High School"],
  FL: ["Miami Senior High School", "Coral Gables High School", "Palmetto High School", "Flanagan High School",
       "Edgewater High School", "Dr. Phillips High School"],
  TN: ["Hillsboro High School Nashville", "Overton High School", "Memphis Central High School", "East High School Memphis"],
  KY: ["Ballard High School", "Eastern High School Louisville", "Manual High School Louisville"],
  VA: ["Thomas Jefferson High School", "Langley High School", "West Springfield High School", "Ocean Lakes High School"],
  SC: ["A.C. Flora High School", "Dreher High School", "Spring Valley High School Columbia"],
  LA: ["Jesuit High School New Orleans", "De La Salle High School", "John Curtis Christian School"],
  AL: ["Mountain Brook High School", "Vestavia Hills High School", "Bob Jones High School"],
  IL: ["Lane Technical College Prep", "Whitney Young Magnet High School", "Jones College Prep", "Walter Payton College Prep"],
  MI: ["Cass Technical High School", "Renaissance High School Detroit", "Forest Hills Central High School"],
  OH: ["Upper Arlington High School", "Dublin Jerome High School", "Westerville Central High School",
       "St. Ignatius High School Cleveland", "Elder High School"],
  IN: ["Carmel High School", "Cathedral High School Indianapolis", "Bishop Chatard High School"],
  WI: ["Marquette University High School", "Homestead High School Milwaukee", "Madison West High School"],
  MN: ["Eden Prairie High School", "Edina High School", "Wayzata High School", "Minnetonka High School"],
  MO: ["Ladue Horton Watkins High School", "Clayton High School MO", "Pattonville High School"],
  NE: ["Millard North High School", "Westside High School Omaha", "Lincoln High School NE"],
  TX: ["Allen High School", "Plano Senior High School", "Westlake High School Austin",
       "Bellaire High School", "Kinkaid School", "St. Mark's School of Texas"],
  AZ: ["Brophy College Preparatory", "Xavier College Preparatory AZ", "Chaparral High School Scottsdale"],
  NV: ["Green Valley High School", "Coronado High School Las Vegas", "Bishop Gorman High School"],
  NM: ["La Cueva High School", "Cibola High School", "Rio Rancho High School"],
  CA: ["Westchester High School", "Crenshaw High School", "Palisades Charter High School",
       "San Diego High School", "Hoover High School SD", "Lowell High School SF",
       "Gunn High School", "Monta Vista High School", "James Logan High School"],
  WA: ["Bellevue High School", "Interlake High School", "Newport High School Bellevue",
       "Lincoln High School Tacoma", "Stadium High School Tacoma"],
  OR: ["Lincoln High School Portland", "Grant High School Portland", "Wilson High School Portland"],
  CO: ["Cherry Creek High School", "Arapahoe High School", "Chaparral High School CO"],
  UT: ["Juan Diego Catholic High School", "East High School SLC", "Brighton High School"],
};

// Colleges by region
export const COLLEGES_BY_REGION = {
  northeast: [
    "New York University", "Fordham University", "St. John's University", "Hofstra University",
    "Adelphi University", "Pace University", "Long Island University", "Stony Brook University",
    "Temple University", "Drexel University", "La Salle University", "Villanova University",
    "Boston University", "Northeastern University", "UMass Boston", "Suffolk University",
    "American University", "George Washington University", "Howard University", "Georgetown University",
    "University of Maryland", "Towson University", "Loyola University Maryland",
  ],
  southeast: [
    "University of North Carolina Charlotte", "UNC Chapel Hill", "NC State University", "Appalachian State University",
    "Georgia State University", "Kennesaw State University", "Clark Atlanta University", "Spelman College",
    "University of Florida", "Florida State University", "University of Central Florida", "Florida International University",
    "University of South Florida", "Florida Atlantic University",
    "Belmont University", "Tennessee State University", "University of Tennessee",
    "University of Louisville", "Western Kentucky University", "Morehead State University",
    "Virginia Commonwealth University", "George Mason University", "James Madison University",
    "University of South Carolina", "Clemson University", "Coastal Carolina University",
    "Tulane University", "Loyola University New Orleans", "University of New Orleans",
    "University of Alabama at Birmingham", "Auburn University", "Jacksonville State University",
  ],
  midwest: [
    "DePaul University", "Loyola University Chicago", "Illinois State University", "Northern Illinois University",
    "Wayne State University", "Oakland University", "Eastern Michigan University", "Grand Valley State University",
    "Ohio State University", "Ohio University", "Kent State University", "Xavier University Cincinnati",
    "University of Cincinnati", "Butler University", "Indiana University Purdue University Indianapolis",
    "Marquette University", "University of Wisconsin Milwaukee", "Carroll University",
    "University of Minnesota Twin Cities", "Metropolitan State University", "Hamline University",
    "University of Missouri Kansas City", "Rockhurst University", "Missouri State University",
    "University of Nebraska Omaha", "Creighton University",
  ],
  southwest: [
    "University of Texas at Dallas", "University of Texas at Arlington", "Dallas Baptist University",
    "Texas Southern University", "University of Houston", "Houston Baptist University", "Rice University",
    "St. Edward's University", "Texas State University", "Texas A&M San Antonio",
    "University of Texas at San Antonio", "Our Lady of the Lake University",
    "University of Texas at El Paso",
    "Arizona State University", "Grand Canyon University", "University of Arizona",
    "University of Nevada Las Vegas", "Nevada State College",
    "University of New Mexico",
  ],
  west: [
    "California State University Los Angeles", "Cal State Dominguez Hills", "Mount Saint Mary's University",
    "San Diego State University", "National University", "University of San Diego",
    "San Francisco State University", "Golden Gate University", "Cal State East Bay",
    "San Jose State University", "Santa Clara University", "De Anza College",
    "Cal State Sacramento", "UC Davis",
    "Fresno State University", "California Baptist University",
    "University of Washington", "Seattle University", "Western Washington University",
    "Portland State University", "University of Portland", "Linfield University",
    "University of Denver", "Colorado State University", "Metro State University Denver",
    "University of Utah", "Utah Valley University", "Brigham Young University",
  ],
};

// Degree options
export const DEGREES = [
  "Business Administration", "Marketing", "Communications", "Psychology", "Sociology",
  "Computer Science", "Information Technology", "Criminal Justice", "Health Sciences",
  "Nursing", "Education", "Political Science", "History", "English Literature",
  "Finance", "Accounting", "Management", "Human Resources", "Graphic Design",
  "Public Administration", "Social Work", "Biology", "Exercise Science", "Kinesiology",
  "Hospitality Management", "Fashion Design", "Film Studies", "Music", "Art",
  "Environmental Science", "Pre-Med", "Pre-Law", "Economics", "Real Estate",
];
