// Each city entry: { city, state, stateCode, region }
export const US_CITIES = [
  // Northeast
  { city: "New York", state: "New York", stateCode: "NY", region: "northeast" },
  { city: "Brooklyn", state: "New York", stateCode: "NY", region: "northeast" },
  { city: "Queens", state: "New York", stateCode: "NY", region: "northeast" },
  { city: "Buffalo", state: "New York", stateCode: "NY", region: "northeast" },
  { city: "Philadelphia", state: "Pennsylvania", stateCode: "PA", region: "northeast" },
  { city: "Pittsburgh", state: "Pennsylvania", stateCode: "PA", region: "northeast" },
  { city: "Boston", state: "Massachusetts", stateCode: "MA", region: "northeast" },
  { city: "Cambridge", state: "Massachusetts", stateCode: "MA", region: "northeast" },
  { city: "Providence", state: "Rhode Island", stateCode: "RI", region: "northeast" },
  { city: "Hartford", state: "Connecticut", stateCode: "CT", region: "northeast" },
  { city: "Newark", state: "New Jersey", stateCode: "NJ", region: "northeast" },
  { city: "Jersey City", state: "New Jersey", stateCode: "NJ", region: "northeast" },
  { city: "Baltimore", state: "Maryland", stateCode: "MD", region: "northeast" },
  { city: "Washington", state: "District of Columbia", stateCode: "DC", region: "northeast" },
  // Southeast
  { city: "Charlotte", state: "North Carolina", stateCode: "NC", region: "southeast" },
  { city: "Raleigh", state: "North Carolina", stateCode: "NC", region: "southeast" },
  { city: "Atlanta", state: "Georgia", stateCode: "GA", region: "southeast" },
  { city: "Savannah", state: "Georgia", stateCode: "GA", region: "southeast" },
  { city: "Miami", state: "Florida", stateCode: "FL", region: "southeast" },
  { city: "Orlando", state: "Florida", stateCode: "FL", region: "southeast" },
  { city: "Tampa", state: "Florida", stateCode: "FL", region: "southeast" },
  { city: "Jacksonville", state: "Florida", stateCode: "FL", region: "southeast" },
  { city: "Nashville", state: "Tennessee", stateCode: "TN", region: "southeast" },
  { city: "Memphis", state: "Tennessee", stateCode: "TN", region: "southeast" },
  { city: "Louisville", state: "Kentucky", stateCode: "KY", region: "southeast" },
  { city: "Richmond", state: "Virginia", stateCode: "VA", region: "southeast" },
  { city: "Virginia Beach", state: "Virginia", stateCode: "VA", region: "southeast" },
  { city: "Columbia", state: "South Carolina", stateCode: "SC", region: "southeast" },
  { city: "New Orleans", state: "Louisiana", stateCode: "LA", region: "southeast" },
  { city: "Birmingham", state: "Alabama", stateCode: "AL", region: "southeast" },
  // Midwest
  { city: "Chicago", state: "Illinois", stateCode: "IL", region: "midwest" },
  { city: "Naperville", state: "Illinois", stateCode: "IL", region: "midwest" },
  { city: "Detroit", state: "Michigan", stateCode: "MI", region: "midwest" },
  { city: "Grand Rapids", state: "Michigan", stateCode: "MI", region: "midwest" },
  { city: "Columbus", state: "Ohio", stateCode: "OH", region: "midwest" },
  { city: "Cleveland", state: "Ohio", stateCode: "OH", region: "midwest" },
  { city: "Cincinnati", state: "Ohio", stateCode: "OH", region: "midwest" },
  { city: "Indianapolis", state: "Indiana", stateCode: "IN", region: "midwest" },
  { city: "Milwaukee", state: "Wisconsin", stateCode: "WI", region: "midwest" },
  { city: "Madison", state: "Wisconsin", stateCode: "WI", region: "midwest" },
  { city: "Minneapolis", state: "Minnesota", stateCode: "MN", region: "midwest" },
  { city: "St. Paul", state: "Minnesota", stateCode: "MN", region: "midwest" },
  { city: "Kansas City", state: "Missouri", stateCode: "MO", region: "midwest" },
  { city: "St. Louis", state: "Missouri", stateCode: "MO", region: "midwest" },
  { city: "Omaha", state: "Nebraska", stateCode: "NE", region: "midwest" },
  // Southwest
  { city: "Dallas", state: "Texas", stateCode: "TX", region: "southwest" },
  { city: "Houston", state: "Texas", stateCode: "TX", region: "southwest" },
  { city: "Austin", state: "Texas", stateCode: "TX", region: "southwest" },
  { city: "San Antonio", state: "Texas", stateCode: "TX", region: "southwest" },
  { city: "Fort Worth", state: "Texas", stateCode: "TX", region: "southwest" },
  { city: "El Paso", state: "Texas", stateCode: "TX", region: "southwest" },
  { city: "Phoenix", state: "Arizona", stateCode: "AZ", region: "southwest" },
  { city: "Tucson", state: "Arizona", stateCode: "AZ", region: "southwest" },
  { city: "Las Vegas", state: "Nevada", stateCode: "NV", region: "southwest" },
  { city: "Henderson", state: "Nevada", stateCode: "NV", region: "southwest" },
  { city: "Albuquerque", state: "New Mexico", stateCode: "NM", region: "southwest" },
  // West
  { city: "Los Angeles", state: "California", stateCode: "CA", region: "west" },
  { city: "San Diego", state: "California", stateCode: "CA", region: "west" },
  { city: "San Francisco", state: "California", stateCode: "CA", region: "west" },
  { city: "San Jose", state: "California", stateCode: "CA", region: "west" },
  { city: "Sacramento", state: "California", stateCode: "CA", region: "west" },
  { city: "Fresno", state: "California", stateCode: "CA", region: "west" },
  { city: "Oakland", state: "California", stateCode: "CA", region: "west" },
  { city: "Long Beach", state: "California", stateCode: "CA", region: "west" },
  { city: "Seattle", state: "Washington", stateCode: "WA", region: "west" },
  { city: "Tacoma", state: "Washington", stateCode: "WA", region: "west" },
  { city: "Portland", state: "Oregon", stateCode: "OR", region: "west" },
  { city: "Denver", state: "Colorado", stateCode: "CO", region: "west" },
  { city: "Colorado Springs", state: "Colorado", stateCode: "CO", region: "west" },
  { city: "Salt Lake City", state: "Utah", stateCode: "UT", region: "west" },
];

// Nearby/hometown options per city (smaller towns nearby)
export const NEARBY_HOMETOWNS = {
  "New York": ["Yonkers, NY", "White Plains, NY", "Hoboken, NJ", "Stamford, CT", "Long Island City, NY"],
  "Brooklyn": ["Staten Island, NY", "Flatbush, NY", "Bay Ridge, NY", "Flushing, NY", "Yonkers, NY"],
  "Queens": ["Jamaica, NY", "Astoria, NY", "Flushing, NY", "Bayside, NY", "Forest Hills, NY"],
  "Buffalo": ["Cheektowaga, NY", "Tonawanda, NY", "Amherst, NY", "Lockport, NY", "Niagara Falls, NY"],
  "Philadelphia": ["Camden, NJ", "Chester, PA", "Norristown, PA", "Trenton, NJ", "Wilmington, DE"],
  "Pittsburgh": ["Bethel Park, PA", "Monroeville, PA", "Canonsburg, PA", "Aliquippa, PA", "McKeesport, PA"],
  "Boston": ["Quincy, MA", "Somerville, MA", "Brockton, MA", "Lowell, MA", "Lynn, MA"],
  "Cambridge": ["Somerville, MA", "Malden, MA", "Medford, MA", "Watertown, MA", "Arlington, MA"],
  "Providence": ["Cranston, RI", "Pawtucket, RI", "Warwick, RI", "East Providence, RI", "Woonsocket, RI"],
  "Hartford": ["New Britain, CT", "Bristol, CT", "Meriden, CT", "Waterbury, CT", "Glastonbury, CT"],
  "Newark": ["Elizabeth, NJ", "Irvington, NJ", "Bloomfield, NJ", "East Orange, NJ", "Kearny, NJ"],
  "Jersey City": ["Bayonne, NJ", "Hoboken, NJ", "Union City, NJ", "West New York, NJ", "Weehawken, NJ"],
  "Baltimore": ["Towson, MD", "Catonsville, MD", "Dundalk, MD", "Bowie, MD", "Annapolis, MD"],
  "Washington": ["Arlington, VA", "Alexandria, VA", "Silver Spring, MD", "Bethesda, MD", "Rockville, MD"],
  "Charlotte": ["Concord, NC", "Gastonia, NC", "Rock Hill, SC", "Kannapolis, NC", "Monroe, NC"],
  "Raleigh": ["Durham, NC", "Cary, NC", "Garner, NC", "Chapel Hill, NC", "Apex, NC"],
  "Atlanta": ["Marietta, GA", "Sandy Springs, GA", "Smyrna, GA", "Roswell, GA", "Decatur, GA"],
  "Savannah": ["Pooler, GA", "Richmond Hill, GA", "Statesboro, GA", "Hilton Head Island, SC", "Beaufort, SC"],
  "Miami": ["Hialeah, FL", "Coral Gables, FL", "Homestead, FL", "North Miami, FL", "Doral, FL"],
  "Orlando": ["Kissimmee, FL", "Sanford, FL", "Lakeland, FL", "Winter Park, FL", "Altamonte Springs, FL"],
  "Tampa": ["St. Petersburg, FL", "Clearwater, FL", "Brandon, FL", "Largo, FL", "Sarasota, FL"],
  "Jacksonville": ["Orange Park, FL", "St. Augustine, FL", "Fernandina Beach, FL", "Daytona Beach, FL", "Gainesville, FL"],
  "Nashville": ["Murfreesboro, TN", "Franklin, TN", "Smyrna, TN", "Hendersonville, TN", "Clarksville, TN"],
  "Memphis": ["Germantown, TN", "Bartlett, TN", "Southaven, MS", "Cordova, TN", "Collierville, TN"],
  "Louisville": ["Lexington, KY", "Jeffersonville, IN", "Clarksville, IN", "New Albany, IN", "Elizabethtown, KY"],
  "Richmond": ["Chesterfield, VA", "Henrico, VA", "Midlothian, VA", "Glen Allen, VA", "Petersburg, VA"],
  "Virginia Beach": ["Chesapeake, VA", "Norfolk, VA", "Newport News, VA", "Hampton, VA", "Suffolk, VA"],
  "Columbia": ["Lexington, SC", "Irmo, SC", "Florence, SC", "Sumter, SC", "Myrtle Beach, SC"],
  "New Orleans": ["Metairie, LA", "Kenner, LA", "Chalmette, LA", "Gretna, LA", "Harvey, LA"],
  "Birmingham": ["Hoover, AL", "Tuscaloosa, AL", "Huntsville, AL", "Bessemer, AL", "Homewood, AL"],
  "Chicago": ["Evanston, IL", "Aurora, IL", "Rockford, IL", "Joliet, IL", "Waukegan, IL"],
  "Naperville": ["Bolingbrook, IL", "Downers Grove, IL", "Elgin, IL", "Wheaton, IL", "Lisle, IL"],
  "Detroit": ["Warren, MI", "Dearborn, MI", "Livonia, MI", "Sterling Heights, MI", "Ann Arbor, MI"],
  "Grand Rapids": ["Kentwood, MI", "Wyoming, MI", "Muskegon, MI", "Battle Creek, MI", "Kalamazoo, MI"],
  "Columbus": ["Dublin, OH", "Westerville, OH", "Grove City, OH", "Gahanna, OH", "Hilliard, OH"],
  "Cleveland": ["Akron, OH", "Parma, OH", "Elyria, OH", "Lorain, OH", "Strongsville, OH"],
  "Cincinnati": ["Dayton, OH", "Covington, KY", "Florence, KY", "Middletown, OH", "Hamilton, OH"],
  "Indianapolis": ["Carmel, IN", "Fishers, IN", "Anderson, IN", "Bloomington, IN", "Greenwood, IN"],
  "Milwaukee": ["Waukesha, WI", "Kenosha, WI", "Racine, WI", "West Allis, WI", "Brookfield, WI"],
  "Madison": ["Fitchburg, WI", "Sun Prairie, WI", "Middleton, WI", "Janesville, WI", "Beloit, WI"],
  "Minneapolis": ["St. Paul, MN", "Bloomington, MN", "Plymouth, MN", "Brooklyn Park, MN", "Duluth, MN"],
  "St. Paul": ["Woodbury, MN", "Eagan, MN", "Burnsville, MN", "Eden Prairie, MN", "Mankato, MN"],
  "Kansas City": ["Independence, MO", "Overland Park, KS", "Olathe, KS", "Lee's Summit, MO", "Springfield, MO"],
  "St. Louis": ["Chesterfield, MO", "O'Fallon, MO", "Florissant, MO", "Columbia, MO", "Belleville, IL"],
  "Omaha": ["Lincoln, NE", "Bellevue, NE", "Council Bluffs, IA", "Papillion, NE", "Fremont, NE"],
  "Dallas": ["Plano, TX", "Irving, TX", "Garland, TX", "Frisco, TX", "McKinney, TX"],
  "Houston": ["Pearland, TX", "Sugar Land, TX", "League City, TX", "Pasadena, TX", "Baytown, TX"],
  "Austin": ["Round Rock, TX", "Cedar Park, TX", "Georgetown, TX", "Pflugerville, TX", "Kyle, TX"],
  "San Antonio": ["New Braunfels, TX", "Seguin, TX", "Schertz, TX", "Converse, TX", "Universal City, TX"],
  "Fort Worth": ["Arlington, TX", "Mansfield, TX", "North Richland Hills, TX", "Haltom City, TX", "Euless, TX"],
  "El Paso": ["Las Cruces, NM", "Socorro, TX", "Horizon City, TX", "Anthony, TX", "Santa Teresa, NM"],
  "Phoenix": ["Scottsdale, AZ", "Glendale, AZ", "Chandler, AZ", "Gilbert, AZ", "Tempe, AZ"],
  "Tucson": ["Marana, AZ", "Oro Valley, AZ", "Sierra Vista, AZ", "Sahuarita, AZ", "Douglas, AZ"],
  "Las Vegas": ["North Las Vegas, NV", "Summerlin, NV", "Mesquite, NV", "Boulder City, NV", "Pahrump, NV"],
  "Henderson": ["Boulder City, NV", "Pahrump, NV", "Laughlin, NV", "Kingman, AZ", "Bullhead City, AZ"],
  "Albuquerque": ["Rio Rancho, NM", "Santa Fe, NM", "Farmington, NM", "Las Cruces, NM", "Roswell, NM"],
  "Los Angeles": ["Long Beach, CA", "Pasadena, CA", "Burbank, CA", "Glendale, CA", "Santa Monica, CA"],
  "San Diego": ["Chula Vista, CA", "El Cajon, CA", "Escondido, CA", "Oceanside, CA", "San Marcos, CA"],
  "San Francisco": ["Oakland, CA", "Berkeley, CA", "Daly City, CA", "San Mateo, CA", "Fremont, CA"],
  "San Jose": ["Santa Clara, CA", "Sunnyvale, CA", "Milpitas, CA", "Cupertino, CA", "Mountain View, CA"],
  "Sacramento": ["Elk Grove, CA", "Roseville, CA", "Citrus Heights, CA", "Rancho Cordova, CA", "Folsom, CA"],
  "Fresno": ["Clovis, CA", "Visalia, CA", "Bakersfield, CA", "Modesto, CA", "Madera, CA"],
  "Oakland": ["Fremont, CA", "Hayward, CA", "Richmond, CA", "Berkeley, CA", "San Leandro, CA"],
  "Long Beach": ["Compton, CA", "Carson, CA", "Torrance, CA", "Lakewood, CA", "Norwalk, CA"],
  "Seattle": ["Bellevue, WA", "Tacoma, WA", "Renton, WA", "Kirkland, WA", "Redmond, WA"],
  "Tacoma": ["Puyallup, WA", "Lakewood, WA", "Olympia, WA", "Auburn, WA", "Federal Way, WA"],
  "Portland": ["Beaverton, OR", "Gresham, OR", "Hillsboro, OR", "Salem, OR", "Vancouver, WA"],
  "Denver": ["Aurora, CO", "Lakewood, CO", "Arvada, CO", "Westminster, CO", "Thornton, CO"],
  "Colorado Springs": ["Pueblo, CO", "Fountain, CO", "Security-Widefield, CO", "Monument, CO", "Canon City, CO"],
  "Salt Lake City": ["West Valley City, UT", "Provo, UT", "West Jordan, UT", "Orem, UT", "Sandy, UT"],
};

// European travel destinations
export const EUROPE_DESTINATIONS = [
  { place: "Paris, France", date: null },
  { place: "London, England", date: null },
  { place: "Rome, Italy", date: null },
  { place: "Barcelona, Spain", date: null },
  { place: "Amsterdam, Netherlands", date: null },
  { place: "Berlin, Germany", date: null },
  { place: "Prague, Czech Republic", date: null },
  { place: "Vienna, Austria", date: null },
  { place: "Lisbon, Portugal", date: null },
  { place: "Athens, Greece", date: null },
  { place: "Budapest, Hungary", date: null },
  { place: "Copenhagen, Denmark", date: null },
  { place: "Stockholm, Sweden", date: null },
  { place: "Dublin, Ireland", date: null },
  { place: "Brussels, Belgium", date: null },
  { place: "Zurich, Switzerland", date: null },
  { place: "Milan, Italy", date: null },
  { place: "Venice, Italy", date: null },
  { place: "Florence, Italy", date: null },
  { place: "Madrid, Spain", date: null },
  { place: "Seville, Spain", date: null },
  { place: "Dubrovnik, Croatia", date: null },
  { place: "Edinburgh, Scotland", date: null },
  { place: "Munich, Germany", date: null },
  { place: "Hamburg, Germany", date: null },
  { place: "Warsaw, Poland", date: null },
  { place: "Krakow, Poland", date: null },
  { place: "Reykjavik, Iceland", date: null },
  { place: "Santorini, Greece", date: null },
  { place: "Porto, Portugal", date: null },
  { place: "Bruges, Belgium", date: null },
  { place: "Nice, France", date: null },
  { place: "Marseille, France", date: null },
  { place: "Oslo, Norway", date: null },
  { place: "Helsinki, Finland", date: null },
  { place: "Tallinn, Estonia", date: null },
  { place: "Riga, Latvia", date: null },
  { place: "Ljubljana, Slovenia", date: null },
  { place: "Valletta, Malta", date: null },
  { place: "Palermo, Italy", date: null },
];
