export const AVC = [
  "#1c1c1e",
  "#3a3a3c",
  "#5e5ce6",
  "#0071e3",
  "#30b0c7",
  "#34c759",
  "#ff9f0a",
  "#ff6b35",
  "#bf5af2",
  "#ff375f",
];

export const SC = {
  Active: { bg: "bg-green-bg", text: "text-green-t", dot: "bg-green" },
  Banned: { bg: "bg-red-bg", text: "text-red-t", dot: "bg-red" },
  Flagged: { bg: "bg-orange-bg", text: "text-orange-t", dot: "bg-orange" },
  "Pending Profile": {
    bg: "bg-amber-bg",
    text: "text-amber-t",
    dot: "bg-amber",
  },
};

export const TC = {
  Verified: "bg-accent-l text-[#0058b3]",
  Banned: "bg-red-bg text-red-t",
  Flagged: "bg-orange-bg text-orange-t",
  "Bot Suspect": "bg-purple-bg text-purple-t",
  "New User": "bg-cyan-bg text-cyan-t",
  "Pending Profile": "bg-amber-bg text-amber-t",
};

export const PROFILES = [
  {
    id: 1,
    firstName: "Crescentia",
    lastName: "Wylde",
    dob: "06-17-1993",
    gender: "Female",
    email: "crescentia.wylde93@socialplatform.dev",
    mailPw: "Xv7$Lm!4Bq",
    facebookPw: "Zt5@Wk#9Ny",
    city: "Baltimore, MD",
    hometown: "Frederick, MD",
    workplace: "Johns Hopkins Children's Center",
    position: "Pediatric Palliative Care Nurse",
    bio: "Pediatric palliative care nurse and certified child life specialist. Makes handmade memory boxes for bereaved families.",
    status: "Active",
    profileUrl: "https://platform.dev/profile/crescentia",
    pageUrl: "https://platform.dev/page/crescentia",
    tags: ["Verified"],
    proxy: "192.168.1.101:8080:user101:pass101",
    proxyLocation: "New York, NY",
    profileCreated: "2025-11-03",
    accountCreated: "2025-10-28",
    friends: 247,
    has2FA: true,
    hasPage: true,
    profileSetup: true,
  },
  {
    id: 2,
    firstName: "Peregrin",
    lastName: "Alcott",
    dob: "03-22-1986",
    gender: "Male",
    email: "peregrin.alcott1986@socialplatform.dev",
    mailPw: "Kn8!Bz$6Wv",
    facebookPw: "Jq4@Xm#7Lp",
    city: "Portland, ME",
    hometown: "Bath, ME",
    workplace: "TideGen Ocean Energy",
    position: "Marine Renewable Energy Engineer",
    bio: "Marine renewable energy engineer designing tidal stream turbine arrays for coastal grid integration.",
    status: "Active",
    profileUrl: "https://platform.dev/profile/peregrin",
    pageUrl: "https://platform.dev/page/peregrin",
    tags: ["Verified"],
    proxy: "192.168.1.102:8080:user102:pass102",
    proxyLocation: "Boston, MA",
    profileCreated: "2025-11-10",
    accountCreated: "2025-11-04",
    friends: 134,
    has2FA: true,
    hasPage: true,
    profileSetup: true,
  },
  {
    id: 3,
    firstName: "Talitha",
    lastName: "Moss",
    dob: "10-14-1997",
    gender: "Female",
    email: "talitha.moss@socialplatform.dev",
    mailPw: "Mw5$Xb!9Jz",
    facebookPw: "Rp3@Vn#6Yk",
    city: "Los Angeles, CA",
    hometown: "Long Beach, CA",
    workplace: "LA County DA's Office",
    position: "Deputy District Attorney",
    bio: "Victim-centered prosecutor specializing in human trafficking and domestic violence cases.",
    status: "Pending Profile",
    profileUrl: "",
    pageUrl: "",
    tags: ["Pending Profile"],
    proxy: "",
    proxyLocation: "Chicago, IL",
    profileCreated: "2026-01-15",
    accountCreated: "2026-01-12",
    friends: 18,
    has2FA: false,
    hasPage: false,
    profileSetup: false,
  },
  {
    id: 4,
    firstName: "Hadleigh",
    lastName: "Stanhope",
    dob: "08-05-1984",
    gender: "Male",
    email: "hadleigh84stanhope@socialplatform.dev",
    mailPw: "Zy9$Qn!5Xw",
    facebookPw: "Lk6@Bm#4Ht",
    city: "Virginia Beach, VA",
    hometown: "Norfolk, VA",
    workplace: "VA Emergency Response Training",
    position: "HAZMAT Response Instructor",
    bio: "EOD technician turned HAZMAT emergency response instructor. Mentors veterans transitioning from military service.",
    status: "Active",
    profileUrl: "https://platform.dev/profile/hadleigh",
    pageUrl: "https://platform.dev/page/hadleigh",
    tags: ["Verified"],
    proxy: "192.168.1.104:8080:user104:pass104",
    proxyLocation: "Dallas, TX",
    profileCreated: "2025-10-20",
    accountCreated: "2025-10-15",
    friends: 312,
    has2FA: true,
    hasPage: true,
    profileSetup: true,
  },
  {
    id: 5,
    firstName: "Cormoran",
    lastName: "Aldridge",
    dob: "07-11-1987",
    gender: "Male",
    email: "cormoran.aldridge@socialplatform.dev",
    mailPw: "Xt6$Jv!5Wq",
    facebookPw: "Nb9@Lm#4Yz",
    city: "Seattle, WA",
    hometown: "Spokane, WA",
    workplace: "NarrativEdge Studios",
    position: "Narrative Designer",
    bio: "Independent game narrative designer for three award-winning AAA titles.",
    status: "Flagged",
    profileUrl: "https://platform.dev/profile/cormoran",
    pageUrl: "",
    tags: ["Flagged", "Bot Suspect"],
    proxy: "192.168.1.105:8080:user105:pass105",
    proxyLocation: "Seattle, WA",
    profileCreated: "2025-12-01",
    accountCreated: "2025-11-28",
    friends: 62,
    has2FA: true,
    hasPage: false,
    profileSetup: true,
  },
  {
    id: 6,
    firstName: "Rosalind",
    lastName: "Pryce",
    dob: "05-03-2000",
    gender: "Female",
    email: "rosalind.pryce2000@socialplatform.dev",
    mailPw: "Jm4!Bv$9Yz",
    facebookPw: "Wd7@Xp#2Lk",
    city: "Providence, RI",
    hometown: "Pawtucket, RI",
    workplace: "Brown University",
    position: "Pre-Law Student & Reform Advocate",
    bio: "Pre-law student and juvenile justice reform advocate. Published a white paper on youth solitary confinement.",
    status: "Active",
    profileUrl: "https://platform.dev/profile/rosalind",
    pageUrl: "https://platform.dev/page/rosalind",
    tags: ["New User"],
    proxy: "192.168.1.106:8080:user106:pass106",
    proxyLocation: "Miami, FL",
    profileCreated: "2026-02-18",
    accountCreated: "2026-02-15",
    friends: 45,
    has2FA: false,
    hasPage: true,
    profileSetup: false,
  },
  {
    id: 7,
    firstName: "Leofric",
    lastName: "Bauer",
    dob: "11-18-1985",
    gender: "Male",
    email: "leofric.bauer@socialplatform.dev",
    mailPw: "Qn9$Ht!6Wv",
    facebookPw: "Pb3@Mz#7Yx",
    city: "Charlotte, NC",
    hometown: "Raleigh, NC",
    workplace: "FireStruct Forensic Engineering",
    position: "Forensic Structural Fire Investigator",
    bio: "Forensic structural fire investigator and expert witness. Has testified in 60+ insurance litigation cases.",
    status: "Banned",
    profileUrl: "",
    pageUrl: "",
    tags: ["Banned"],
    proxy: "",
    proxyLocation: "Atlanta, GA",
    profileCreated: "2025-09-12",
    accountCreated: "2025-09-08",
    friends: 0,
    has2FA: false,
    hasPage: false,
    profileSetup: false,
  },
  {
    id: 8,
    firstName: "Caoimhe",
    lastName: "Dunmore",
    dob: "04-26-1994",
    gender: "Female",
    email: "caoimhe.dunmore@socialplatform.dev",
    mailPw: "Sk2!Cy$7Rp",
    facebookPw: "Xe8@Vn#4Jq",
    city: "Morgantown, WV",
    hometown: "Elkins, WV",
    workplace: "Hollow Mountain Community Radio",
    position: "Founder & Station Director",
    bio: "Community radio station founder and audio documentarian telling stories of rural Appalachian communities.",
    status: "Active",
    profileUrl: "https://platform.dev/profile/caoimhe",
    pageUrl: "https://platform.dev/page/caoimhe",
    tags: ["Verified"],
    proxy: "192.168.1.108:8080:user108:pass108",
    proxyLocation: "Denver, CO",
    profileCreated: "2025-10-30",
    accountCreated: "2025-10-25",
    friends: 188,
    has2FA: true,
    hasPage: true,
    profileSetup: true,
  },
  {
    id: 9,
    firstName: "Tancred",
    lastName: "Holloway",
    dob: "09-08-1982",
    gender: "Male",
    email: "tancred.holloway@socialplatform.dev",
    mailPw: "Lv5$Jw!9Mc",
    facebookPw: "Tg3@Yk#6Bz",
    city: "Charlotte, NC",
    hometown: "Concord, NC",
    workplace: "Apex Race Engineering",
    position: "CFD Aerodynamics Engineer",
    bio: "CFD aerodynamics engineer optimizing performance for Formula E. Former motorsport test driver.",
    status: "Active",
    profileUrl: "https://platform.dev/profile/tancred",
    pageUrl: "https://platform.dev/page/tancred",
    tags: ["Verified"],
    proxy: "192.168.1.109:8080:user109:pass109",
    proxyLocation: "Phoenix, AZ",
    profileCreated: "2025-11-22",
    accountCreated: "2025-11-18",
    friends: 521,
    has2FA: true,
    hasPage: true,
    profileSetup: true,
  },
  {
    id: 10,
    firstName: "Silvana",
    lastName: "Pringle",
    dob: "02-11-1996",
    gender: "Female",
    email: "silvana.pringle@socialplatform.dev",
    mailPw: "Rx4!Pb$2Wn",
    facebookPw: "Hy9@Lc#7Zt",
    city: "New Haven, CT",
    hometown: "Bridgeport, CT",
    workplace: "Blue Harvest Ocean Farm",
    position: "Regenerative Aquaculture Farmer",
    bio: "Regenerative ocean farmer cultivating seaweed and shellfish in a multi-species aquaculture system.",
    status: "Pending Profile",
    profileUrl: "",
    pageUrl: "",
    tags: ["Pending Profile", "New User"],
    proxy: "",
    proxyLocation: "Las Vegas, NV",
    profileCreated: "2026-01-30",
    accountCreated: "2026-01-27",
    friends: 9,
    has2FA: false,
    hasPage: false,
    profileSetup: false,
  },
  {
    id: 11,
    firstName: "Zenobia",
    lastName: "Holloway",
    dob: "05-28-1991",
    gender: "Female",
    email: "zenobia91holloway@socialplatform.dev",
    mailPw: "Lv8$Xm!4Wz",
    facebookPw: "Kq5@Yt#9Nb",
    city: "Atlanta, GA",
    hometown: "Augusta, GA",
    workplace: "Emory Maternal Fetal Medicine Center",
    position: "Diagnostic Ultrasound Specialist",
    bio: "Maternal-fetal ultrasound specialist. Has performed 10,000+ diagnostic scans.",
    status: "Active",
    profileUrl: "https://platform.dev/profile/zenobia",
    pageUrl: "https://platform.dev/page/zenobia",
    tags: ["Verified"],
    proxy: "192.168.1.111:8080:user111:pass111",
    proxyLocation: "San Diego, CA",
    profileCreated: "2025-12-14",
    accountCreated: "2025-12-10",
    friends: 390,
    has2FA: true,
    hasPage: true,
    profileSetup: true,
  },
  {
    id: 12,
    firstName: "Aldhelm",
    lastName: "Strand",
    dob: "09-16-1986",
    gender: "Male",
    email: "aldhelm86strand@socialplatform.dev",
    mailPw: "Wz5$Jv!8Xk",
    facebookPw: "Bm9@Lp#4Yq",
    city: "Key West, FL",
    hometown: "Tampa, FL",
    workplace: "Gulf Coast Marine Debris Research",
    position: "Marine Debris Researcher",
    bio: "Freediving record holder & marine debris researcher quantifying microplastics in Gulf of Mexico.",
    status: "Active",
    profileUrl: "https://platform.dev/profile/aldhelm",
    pageUrl: "https://platform.dev/page/aldhelm",
    tags: ["Verified"],
    proxy: "192.168.1.112:8080:user112:pass112",
    proxyLocation: "Houston, TX",
    profileCreated: "2025-11-05",
    accountCreated: "2025-11-01",
    friends: 276,
    has2FA: true,
    hasPage: true,
    profileSetup: true,
  },
  {
    id: 13,
    firstName: "Celestia",
    lastName: "Dunmore",
    dob: "02-19-1998",
    gender: "Female",
    email: "celestia1998dunmore@socialplatform.dev",
    mailPw: "Xp4!Wv$7Mz",
    facebookPw: "Jk9@Vn#5Lq",
    city: "Huntsville, TX",
    hometown: "Houston, TX",
    workplace: "TX Dept of Criminal Justice Education",
    position: "Prison Education Coordinator",
    bio: "Prison education coordinator who enrolled 200+ incarcerated students in college-credit programs.",
    status: "Flagged",
    profileUrl: "https://platform.dev/profile/celestia",
    pageUrl: "",
    tags: ["Flagged"],
    proxy: "192.168.1.113:8080:user113:pass113",
    proxyLocation: "Detroit, MI",
    profileCreated: "2026-01-08",
    accountCreated: "2026-01-04",
    friends: 34,
    has2FA: true,
    hasPage: false,
    profileSetup: false,
  },
  {
    id: 14,
    firstName: "Leofric",
    lastName: "Whitmore",
    dob: "07-07-1984",
    gender: "Male",
    email: "leofric84whitmore@socialplatform.dev",
    mailPw: "Zt7$Kn!5Wv",
    facebookPw: "Mj4@Lx#8Yb",
    city: "Portland, OR",
    hometown: "Corvallis, OR",
    workplace: "Timber Elevation Structural Engineering",
    position: "Mass Timber Structural Engineer",
    bio: "Structural timber engineer designing low-carbon mass timber buildings over 10 stories tall.",
    status: "Active",
    profileUrl: "https://platform.dev/profile/leofricw",
    pageUrl: "https://platform.dev/page/leofricw",
    tags: ["Verified"],
    proxy: "192.168.1.114:8080:user114:pass114",
    proxyLocation: "San Francisco, CA",
    profileCreated: "2025-10-05",
    accountCreated: "2025-10-01",
    friends: 443,
    has2FA: true,
    hasPage: true,
    profileSetup: true,
  },
  {
    id: 15,
    firstName: "Iolanthe",
    lastName: "Stanhope",
    dob: "11-04-1995",
    gender: "Female",
    email: "iolanthe95stanhope@socialplatform.dev",
    mailPw: "Rn6!Zb$4Xm",
    facebookPw: "Vp8@Lk#7Wq",
    city: "San Jose, CA",
    hometown: "Fremont, CA",
    workplace: "NovaDrive Autonomous Systems",
    position: "AV Safety Validation Engineer",
    bio: "AV safety engineer running edge-case simulation testing for self-driving systems. Amateur rally car driver.",
    status: "Active",
    profileUrl: "https://platform.dev/profile/iolanthe",
    pageUrl: "https://platform.dev/page/iolanthe",
    tags: ["Verified"],
    proxy: "192.168.1.115:8080:user115:pass115",
    proxyLocation: "Los Angeles, CA",
    profileCreated: "2025-09-28",
    accountCreated: "2025-09-24",
    friends: 587,
    has2FA: true,
    hasPage: true,
    profileSetup: true,
  },
];

export const PROFILE_EXTRA = {
  1: {
    personal: { relationshipStatus: "In a Relationship", relationshipStatusSince: "2023", languages: ["English", "Spanish"] },
    work: [
      { company: "Johns Hopkins Children's Center", position: "Pediatric Palliative Care Nurse", from: "2019", current: true, to: null, city: "Baltimore, MD" },
      { company: "Frederick Regional Health System", position: "Registered Nurse", from: "2015", current: false, to: "2019", city: "Frederick, MD" },
    ],
    education: {
      college: { name: "University of Maryland School of Nursing", from: "2011", to: "2015", graduated: true, degree: "BSN, Nursing" },
      highSchool: { name: "Frederick High School", from: "2007", to: "2011", graduated: true },
    },
    hobbies: ["Calligraphy", "Hiking", "Pottery", "Volunteering", "Reading"],
    interests: { music: ["Indie Folk", "Classical", "Ambient"], tvShows: ["Grey's Anatomy", "Ted Lasso", "The Bear"], movies: ["The Pursuit of Happyness", "Encanto"], games: [], sportsTeams: ["Baltimore Ravens"] },
    travel: [{ place: "Costa Rica", date: "2022-08" }, { place: "Italy", date: "2019-06" }],
    otherNames: ["Cressy Wylde"],
  },
  2: {
    personal: { relationshipStatus: "In a Relationship", relationshipStatusSince: "2024", languages: ["English"] },
    work: [
      { company: "TideGen Ocean Energy", position: "Marine Renewable Energy Engineer", from: "2021", current: true, to: null, city: "Portland, ME" },
      { company: "Coastal Wind Partners", position: "Offshore Systems Engineer", from: "2016", current: false, to: "2021", city: "Boston, MA" },
    ],
    education: {
      college: { name: "University of Maine", from: "2004", to: "2008", graduated: true, degree: "B.S. Ocean Engineering" },
      highSchool: { name: "Morse High School", from: "2000", to: "2004", graduated: true },
    },
    hobbies: ["Kayaking", "Rock Climbing", "Fishing", "Woodworking"],
    interests: { music: ["Classic Rock", "Blues"], tvShows: ["Deadliest Catch", "The Office"], movies: ["Cast Away", "The Martian"], games: ["Chess"], sportsTeams: ["New England Patriots", "Boston Celtics"] },
    travel: [{ place: "Norway", date: "2023-07" }],
    otherNames: ["Perry Alcott"],
  },
  3: {
    personal: { relationshipStatus: "Single", relationshipStatusSince: null, languages: ["English", "Mandarin"] },
    work: [
      { company: "LA County DA's Office", position: "Deputy District Attorney", from: "2022", current: true, to: null, city: "Los Angeles, CA" },
      { company: "Public Defender's Office", position: "Staff Attorney", from: "2020", current: false, to: "2022", city: "Long Beach, CA" },
    ],
    education: {
      college: { name: "UCLA School of Law", from: "2017", to: "2020", graduated: true, degree: "J.D." },
      highSchool: { name: "Long Beach Polytechnic High", from: "2011", to: "2015", graduated: true },
    },
    hobbies: ["Running", "Cooking", "Reading"],
    interests: { music: ["R&B", "Jazz", "Hip-Hop"], tvShows: ["How to Get Away with Murder", "Suits"], movies: ["Just Mercy", "A Time to Kill"], games: [], sportsTeams: ["LA Lakers"] },
    travel: [{ place: "Japan", date: "2021-11" }],
    otherNames: ["Tali Moss"],
  },
  4: {
    personal: { relationshipStatus: "Married", relationshipStatusSince: "2022", languages: ["English"] },
    work: [
      { company: "VA Emergency Response Training", position: "HAZMAT Response Instructor", from: "2018", current: true, to: null, city: "Virginia Beach, VA" },
      { company: "US Marine Corps", position: "EOD Technician", from: "2003", current: false, to: "2018", city: "Various" },
    ],
    education: {
      college: { name: "Old Dominion University", from: "2018", to: "2021", graduated: true, degree: "B.S. Emergency Management" },
      highSchool: { name: "Granby High School", from: "1999", to: "2003", graduated: true },
    },
    hobbies: ["Hunting", "Weight Training", "Woodworking", "Fishing"],
    interests: { music: ["Country", "Classic Rock"], tvShows: ["Band of Brothers", "Yellowstone"], movies: ["Lone Survivor", "American Sniper"], games: ["Call of Duty"], sportsTeams: ["Virginia Tech Hokies", "Washington Commanders"] },
    travel: [{ place: "Ireland", date: "2020-08" }, { place: "Germany", date: "2017-03" }],
    otherNames: ["Had Stanhope"],
  },
  5: {
    personal: { relationshipStatus: "In a Relationship", relationshipStatusSince: "2023", languages: ["English", "French"] },
    work: [
      { company: "NarrativEdge Studios", position: "Narrative Designer", from: "2020", current: true, to: null, city: "Seattle, WA" },
      { company: "Bungie", position: "Junior Writer", from: "2017", current: false, to: "2020", city: "Bellevue, WA" },
    ],
    education: {
      college: { name: "University of Washington", from: "2005", to: "2009", graduated: true, degree: "B.A. Creative Writing" },
      highSchool: { name: "Lewis & Clark High School", from: "2001", to: "2005", graduated: true },
    },
    hobbies: ["Dungeons & Dragons", "Screenwriting", "Coffee Roasting"],
    interests: { music: ["Synthwave", "Indie Rock", "Film Scores"], tvShows: ["The Last of Us", "Dark", "Severance"], movies: ["Blade Runner 2049", "Annihilation", "Arrival"], games: ["Disco Elysium", "Mass Effect", "Elden Ring"], sportsTeams: ["Seattle Mariners"] },
    travel: [{ place: "France", date: "2022-05" }],
    otherNames: ["Cor Aldridge", "C. Aldridge"],
  },
  6: {
    personal: { relationshipStatus: "In a Relationship", relationshipStatusSince: "2024", languages: ["English", "Portuguese"] },
    work: [
      { company: "Brown University", position: "Pre-Law Student & Reform Advocate", from: "2022", current: true, to: null, city: "Providence, RI" },
      { company: "Rhode Island Public Defender", position: "Legal Intern", from: "2023", current: false, to: "2023", city: "Providence, RI" },
    ],
    education: {
      college: { name: "Brown University", from: "2022", to: null, graduated: false, degree: "B.A. Political Science (in progress)" },
      highSchool: { name: "Tolman High School", from: "2018", to: "2022", graduated: true },
    },
    hobbies: ["Poetry Writing", "Photography", "Debate"],
    interests: { music: ["Indie Pop", "Folk", "Afrobeats"], tvShows: ["The Good Place", "Pose"], movies: ["Selma", "Promising Young Woman"], games: [], sportsTeams: ["Boston Red Sox"] },
    travel: [{ place: "Brazil", date: "2023-12" }],
    otherNames: ["Rosie Pryce"],
  },
  7: {
    personal: { relationshipStatus: "Single", relationshipStatusSince: null, languages: ["English", "German"] },
    work: [
      { company: "FireStruct Forensic Engineering", position: "Forensic Structural Fire Investigator", from: "2015", current: true, to: null, city: "Charlotte, NC" },
    ],
    education: {
      college: { name: "NC State University", from: "2003", to: "2008", graduated: true, degree: "B.S. Civil Engineering" },
      highSchool: { name: "Enloe High School", from: "1999", to: "2003", graduated: true },
    },
    hobbies: ["Model Railroading", "Bonsai", "Chess"],
    interests: { music: ["Classical", "Jazz"], tvShows: ["Forensic Files", "Engineering Disasters"], movies: ["The Big Short", "Sully"], games: ["Chess.com"], sportsTeams: ["Carolina Panthers"] },
    travel: [{ place: "Germany", date: "2019-09" }],
    otherNames: ["Leo Bauer", "L. Bauer"],
  },
  8: {
    personal: { relationshipStatus: "In a Relationship", relationshipStatusSince: "2023", languages: ["English", "Irish Gaelic"] },
    work: [
      { company: "Hollow Mountain Community Radio", position: "Founder & Station Director", from: "2018", current: true, to: null, city: "Morgantown, WV" },
    ],
    education: {
      college: { name: "West Virginia University", from: "2012", to: "2016", graduated: true, degree: "B.A. Journalism & Broadcasting" },
      highSchool: { name: "Elkins High School", from: "2008", to: "2012", graduated: true },
    },
    hobbies: ["Field Recording", "Canning & Preserving", "Hiking", "Banjo"],
    interests: { music: ["Appalachian Folk", "Bluegrass", "Americana", "Irish Traditional"], tvShows: ["Schitt's Creek", "Miniseries documentaries"], movies: ["Beasts of the Southern Wild", "O Brother Where Art Thou?"], games: [], sportsTeams: ["WVU Mountaineers"] },
    travel: [{ place: "Ireland", date: "2021-06" }, { place: "Nashville, TN", date: "2022-04" }],
    otherNames: ["Kiva Dunmore", "Kay Dunmore"],
  },
  9: {
    personal: { relationshipStatus: "Married", relationshipStatusSince: "2022", languages: ["English", "Italian"] },
    work: [
      { company: "Apex Race Engineering", position: "CFD Aerodynamics Engineer", from: "2017", current: true, to: null, city: "Charlotte, NC" },
      { company: "Williams Racing", position: "Simulation Engineer", from: "2013", current: false, to: "2017", city: "Grove, UK" },
    ],
    education: {
      college: { name: "Imperial College London", from: "2000", to: "2004", graduated: true, degree: "M.Eng. Aerospace Engineering" },
      highSchool: { name: "Concord High School", from: "1996", to: "2000", graduated: true },
    },
    hobbies: ["Karting", "Mountain Biking", "Scale Modeling", "Photography"],
    interests: { music: ["Electronic", "Italian Pop", "Post-Rock"], tvShows: ["Formula 1: Drive to Survive", "Top Gear"], movies: ["Rush", "Ford v Ferrari", "Le Mans '66"], games: ["F1 2024", "Gran Turismo"], sportsTeams: ["Ferrari F1", "Charlotte FC"] },
    travel: [{ place: "Italy (Monza GP)", date: "2023-09" }, { place: "Monaco GP", date: "2022-05" }],
    otherNames: ["Tan Holloway"],
  },
  10: {
    personal: { relationshipStatus: "Single", relationshipStatusSince: null, languages: ["English", "French"] },
    work: [
      { company: "Blue Harvest Ocean Farm", position: "Regenerative Aquaculture Farmer", from: "2023", current: true, to: null, city: "New Haven, CT" },
    ],
    education: {
      college: { name: "University of Connecticut", from: "2014", to: "2018", graduated: true, degree: "B.S. Marine Sciences" },
      highSchool: { name: "Harding High School", from: "2010", to: "2014", graduated: true },
    },
    hobbies: ["Freediving", "Fermentation", "Botanical Drawing", "Sailing"],
    interests: { music: ["Ambient", "World Music", "Jazz"], tvShows: ["Our Planet", "Chef's Table"], movies: ["My Octopus Teacher", "Seaspiracy"], games: [], sportsTeams: ["UConn Huskies"] },
    travel: [{ place: "Denmark", date: "2022-09" }],
    otherNames: ["Sil Pringle", "Silvie Pringle"],
  },
  11: {
    personal: { relationshipStatus: "Married", relationshipStatusSince: "2023", languages: ["English", "Amharic"] },
    work: [
      { company: "Emory Maternal Fetal Medicine Center", position: "Diagnostic Ultrasound Specialist", from: "2018", current: true, to: null, city: "Atlanta, GA" },
      { company: "Augusta University Medical Center", position: "Sonographer", from: "2014", current: false, to: "2018", city: "Augusta, GA" },
    ],
    education: {
      college: { name: "Georgia State University", from: "2009", to: "2013", graduated: true, degree: "B.S. Diagnostic Medical Sonography" },
      highSchool: { name: "T.W. Josey High School", from: "2005", to: "2009", graduated: true },
    },
    hobbies: ["Afrobeats Dance", "Gardening", "Bible Study", "Photography"],
    interests: { music: ["Gospel", "Afrobeats", "R&B"], tvShows: ["Grey's Anatomy", "Abbott Elementary", "Queen Sugar"], movies: ["Everything Everywhere All at Once", "Black Panther"], games: [], sportsTeams: ["Atlanta Falcons", "Atlanta Braves"] },
    travel: [{ place: "Ethiopia", date: "2020-01" }, { place: "Ghana", date: "2022-12" }],
    otherNames: ["Zenie Holloway", "Z. Holloway"],
  },
  12: {
    personal: { relationshipStatus: "In a Relationship", relationshipStatusSince: "2022", languages: ["English", "Spanish"] },
    work: [
      { company: "Gulf Coast Marine Debris Research", position: "Marine Debris Researcher", from: "2016", current: true, to: null, city: "Key West, FL" },
      { company: "NOAA Marine Debris Program", position: "Research Technician", from: "2012", current: false, to: "2016", city: "Tampa, FL" },
    ],
    education: {
      college: { name: "University of Florida", from: "2004", to: "2008", graduated: true, degree: "B.S. Environmental Science" },
      highSchool: { name: "Hillsborough High School", from: "2000", to: "2004", graduated: true },
    },
    hobbies: ["Freediving", "Spearfishing", "Sailing", "Photography"],
    interests: { music: ["Reggae", "Tropical House", "Classic Rock"], tvShows: ["Blue Planet II", "Deadliest Catch"], movies: ["The Big Blue", "Chasing Coral"], games: ["Minecraft"], sportsTeams: ["Miami Dolphins", "Tampa Bay Rays"] },
    travel: [{ place: "Maldives", date: "2021-10" }, { place: "Belize", date: "2019-07" }],
    otherNames: ["Al Strand", "Ald Strand"],
  },
  13: {
    personal: { relationshipStatus: "In a Relationship", relationshipStatusSince: "2024", languages: ["English", "Spanish"] },
    work: [
      { company: "TX Dept of Criminal Justice Education", position: "Prison Education Coordinator", from: "2020", current: true, to: null, city: "Huntsville, TX" },
      { company: "Houston ISD", position: "High School History Teacher", from: "2016", current: false, to: "2020", city: "Houston, TX" },
    ],
    education: {
      college: { name: "Texas Southern University", from: "2012", to: "2016", graduated: true, degree: "B.A. History & Education" },
      highSchool: { name: "Lamar High School", from: "2008", to: "2012", graduated: true },
    },
    hobbies: ["Grant Writing", "Book Club", "Community Gardening", "Yoga"],
    interests: { music: ["Soul", "Hip-Hop", "Gospel"], tvShows: ["Orange is the New Black", "Abbott Elementary", "Queen Sugar"], movies: ["Just Mercy", "13th", "The Shawshank Redemption"], games: [], sportsTeams: ["Houston Texans", "Houston Astros"] },
    travel: [{ place: "Mexico City", date: "2022-03" }],
    otherNames: ["Celly Dunmore", "C. Dunmore"],
  },
  14: {
    personal: { relationshipStatus: "Married", relationshipStatusSince: "2022", languages: ["English", "German"] },
    work: [
      { company: "Timber Elevation Structural Engineering", position: "Mass Timber Structural Engineer", from: "2016", current: true, to: null, city: "Portland, OR" },
      { company: "KPFF Consulting Engineers", position: "Structural Engineer", from: "2009", current: false, to: "2016", city: "Corvallis, OR" },
    ],
    education: {
      college: { name: "Oregon State University", from: "2001", to: "2006", graduated: true, degree: "M.S. Civil & Structural Engineering" },
      highSchool: { name: "Corvallis High School", from: "1997", to: "2001", graduated: true },
    },
    hobbies: ["Timber Framing", "Rock Climbing", "Cycling", "Homebrewing"],
    interests: { music: ["Pacific Northwest Indie", "Folk", "Post-Rock"], tvShows: ["How It's Made", "Grand Designs UK"], movies: ["The Revenant", "Koyaanisqatsi"], games: ["Cities: Skylines"], sportsTeams: ["Portland Trail Blazers", "Oregon Ducks"] },
    travel: [{ place: "Austria (timber architecture tour)", date: "2023-04" }, { place: "Japan", date: "2018-10" }],
    otherNames: ["Leo Whitmore", "L.J. Whitmore"],
  },
  15: {
    personal: { relationshipStatus: "In a Relationship", relationshipStatusSince: "2023", languages: ["English", "Greek"] },
    work: [
      { company: "NovaDrive Autonomous Systems", position: "AV Safety Validation Engineer", from: "2020", current: true, to: null, city: "San Jose, CA" },
      { company: "Waymo", position: "Test & Evaluation Engineer", from: "2016", current: false, to: "2020", city: "Mountain View, CA" },
    ],
    education: {
      college: { name: "Stanford University", from: "2011", to: "2015", graduated: true, degree: "B.S. Mechanical Engineering" },
      highSchool: { name: "Mission San Jose High School", from: "2007", to: "2011", graduated: true },
    },
    hobbies: ["Rally Car Racing", "Rock Climbing", "Drone FPV Racing", "3D Printing"],
    interests: { music: ["Electronic", "Greek Pop", "Alt-Rock"], tvShows: ["Black Mirror", "Halt and Catch Fire", "Severance"], movies: ["Mad Max: Fury Road", "Ghost in the Shell", "The Matrix"], games: ["Forza Motorsport", "Cyberpunk 2077"], sportsTeams: ["San Jose Sharks", "Golden State Warriors"] },
    travel: [{ place: "Greece", date: "2022-07" }, { place: "Finland (Nurburgring trip)", date: "2021-08" }],
    otherNames: ["Io Stanhope", "Lanthe"],
  },
};

